'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),W=1440,H=810;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),lerp=(a,b,t)=>a+(b-a)*t,rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)],shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a;};
const KEY='dentphoto-action-v1',FONT='"Apple SD Gothic Neo","Malgun Gothic",sans-serif';
const DEFAULT={version:1,teeth:0,film:0,runs:0,wins:0,clues:[],residents:[],bossKnown:false,upgrades:{health:0,parry:0,flask:0,smile:0},flail:false,sound:true,reduced:false};
let meta=structuredClone(DEFAULT),saveFailed=false;try{let d=JSON.parse(localStorage.getItem(KEY));if(validMeta(d))meta=d;}catch(e){}
function validMeta(d){return d&&d.version===1&&['teeth','film','runs','wins'].every(k=>Number.isInteger(d[k])&&d[k]>=0&&d[k]<1e8)&&['clues','residents'].every(k=>Array.isArray(d[k])&&d[k].every(x=>typeof x==='string'&&x.length<50))&&d.upgrades&&['health','parry','flask','smile'].every(k=>Number.isInteger(d.upgrades[k])&&d.upgrades[k]>=0&&d.upgrades[k]<=5)&&typeof d.flail==='boolean'&&typeof d.bossKnown==='boolean'&&typeof d.sound==='boolean'&&typeof d.reduced==='boolean';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(meta));}catch(e){if(!saveFailed){saveFailed=true;toast('브라우저 저장을 사용할 수 없습니다. 메뉴에서 기록을 내보내 주세요.');}}}
const BG=new Image();BG.src=ASSETS.harbor;
const keys=new Set(),pressed=new Set();let lastPad={},inputDevice='keyboard',audioCtx=null,musicTick=0,musicClock=0;
const G={mode:'title',t:0,dt:0,room:0,world:2600,camera:0,shake:0,hitstop:0,flash:0,particles:[],texts:[],slashes:[],projectiles:[],ghosts:[],enemies:[],platforms:[],decor:[],doors:[],npcs:[],ropes:[],drops:[],cleared:false,clearTimer:0,toastTime:0,prompt:'',run:null,p:null,layout:0,transitioning:false,banner:null,boss:null,ambient:[],startedAt:0};
const BOONS=[
{id:'healparry',who:'술집 주인 로사',name:'한 잔의 여유',icon:'♨',desc:'받아치기 성공마다 체면 5 회복.',quote:'“말도 목을 축여야 잘 나오지.”'},
{id:'secondlife',who:'술집 주인 로사',name:'외상은 한 번만',icon:'♡',desc:'쓰러질 때 한 번, 체면 35%로 다시 일어납니다.',quote:'“계산은 살아 돌아와서 해.”'},
{id:'heart',who:'술집 주인 로사',name:'든든한 저녁',icon:'❧',desc:'이번 항해의 최대 체면 +20, 즉시 20 회복.',quote:'“빈속에 허풍 떨면 쓰러져.”'},
{id:'dashlight',who:'등대지기 노아',name:'발끝의 등불',icon:'✦',desc:'구르기가 끝날 때 섬광. 주변 적을 1초 기절시킵니다.',quote:'“빛도 가끔은 발이 빨라야지.”'},
{id:'stunparry',who:'등대지기 노아',name:'말문을 닫는 빛',icon:'☼',desc:'받아치기의 피해 +12, 적 기절 시간 +1초.',quote:'“눈부신 대사는 원래 아프단다.”'},
{id:'radiance',who:'등대지기 노아',name:'다시 켜진 등대',icon:'◈',desc:'필살 대사 피해 +40. 관중 웃음을 즉시 25 얻습니다.',quote:'“네 웃음이 길을 밝혀 줄 거야.”'},
{id:'poison',who:'생선 장수 마리',name:'비린내 나는 칼끝',icon:'≋',desc:'공격에 독 추가. 3초 동안 매초 피해 5.',quote:'“싱싱함에도 유통기한은 있지.”'},
{id:'slip',who:'생선 장수 마리',name:'미끄러운 협상',icon:'⌁',desc:'3타 마무리가 적을 더 멀리 밀고 1.4초 기절시킵니다.',quote:'“말도 발도 헛디디면 큰일이지.”'},
{id:'chicken',who:'생선 장수 마리',name:'닭 대신 생선',icon:'♧',desc:'고무 닭의 피해 +16, 재사용 시간 2초 감소.',quote:'“맛은 몰라도 소리는 싱싱해.”'}
];
const LAYOUTS=[
[[350,515,230],[770,425,210],[1100,525,260],[1530,470,230],[1950,535,250]],
[[280,540,200],[580,445,230],[930,350,240],[1280,460,220],[1740,535,300]],
[[420,500,280],[920,535,220],[1220,425,230],[1670,340,250],[2050,500,180]],
[[300,540,250],[780,540,250],[1170,485,280],[1610,405,250],[2010,530,180]],
[[270,450,220],[650,520,280],[1100,450,220],[1530,520,240],[1950,430,230]],
[[420,545,180],[760,455,180],[1100,365,260],[1500,450,230],[1850,545,260]],
[[280,540,350],[900,450,320],[1430,520,270],[1880,410,300]],
[[380,420,260],[760,525,220],[1220,430,280],[1710,520,200],[2040,440,180]],
[[290,520,220],[660,410,230],[1050,520,330],[1570,425,280],[2010,520,170]],
[[380,540,230],[780,455,310],[1240,350,250],[1650,470,250],[2000,540,180]],
[[300,470,310],[890,520,260],[1270,420,240],[1680,520,240],[2010,430,180]],
[[350,535,300],[850,435,230],[1230,525,300],[1720,430,250],[2090,520,150]]
];
function player(){return {x:150,y:580,vx:0,vy:0,w:34,h:76,face:1,ground:false,jumps:0,coyote:0,jumpBuffer:0,attack:0,attackCD:0,combo:0,comboTimer:0,queued:false,dash:0,dashCD:0,parry:0,parryCD:0,hurt:0,invul:0,walk:0,skillU:0,skillI:0,rope:null,hitIds:new Set(),trail:0};}
function newRun(){meta.runs++;G.run={hp:100+meta.upgrades.health*12,maxHp:100+meta.upgrades.health*12,gold:0,laugh:0,boons:[],weapon:G.equipped||'sword',revived:false,kills:0,parries:0,rooms:shuffle([...Array(12).keys()]).slice(0,8),reward:'smile',time:0,teethGained:0,filmGained:0};G.startedAt=G.t;G.room=0;save();closeOverlay();loadRoom(0);if(meta.upgrades.smile>0)chooseBoon(true);else if(meta.runs===1)help();}
function resetWorld(){G.offers=null;G.enemies=[];G.projectiles=[];G.particles=[];G.texts=[];G.slashes=[];G.ghosts=[];G.platforms=[];G.decor=[];G.doors=[];G.npcs=[];G.ropes=[];G.drops=[];G.cleared=false;G.clearTimer=0;G.boss=null;G.hitstop=0;G.shake=0;G.camera=0;G.p=player();G.transitioning=false;G.prompt='';}
function hub(){G.offers=null;closeOverlay();resetWorld();G.mode='hub';G.worldMode='hub';G.world=1900;G.run=null;G.platforms=[{x:0,y:650,w:1900,h:170,ground:true},{x:800,y:530,w:240,h:24},{x:1200,y:455,w:210,h:24}];G.npcs=[{x:430,y:650,type:'rosa',name:'로사 · 술집 주인'},{x:970,y:650,type:'lighthouse',name:'노아 · 등대지기'},{x:1340,y:650,type:'smith',name:'마리 · 무기 상인'}];G.doors=[{x:1760,y:650,type:'depart',label:'달빛 부두로 출항'}];G.p.x=240;G.p.y=600;$('#hud').hidden=false;updateHUD();toast(meta.runs?'다시 돌아온 밤의 갈매기. 새 이야기는 끝나지 않았습니다.':'← → 이동 · Space 점프 · 주민 곁에서 E 대화');}
function loadRoom(index){resetWorld();G.mode='play';G.worldMode='play';G.room=index;G.layout=G.run.rooms[index];G.world=index===7?1900:index===6?1600:2600;G.platforms=[{x:0,y:650,w:G.world,h:180,ground:true}];if(index<6){for(let [x,y,w] of LAYOUTS[G.layout])G.platforms.push({x,y,w,h:25});G.ropes=[{x:1110,y:240,bottom:600},{x:1830,y:200,bottom:600}];let types=index===0?['sailor','crab','sailor']:index===3?['elite','rope','crab']:['sailor','crab','rope','sailor',...(index>2?['crab']:[])];types.forEach((type,i)=>{let x=570+i*(1660/(types.length-1));let plat=G.platforms.find(p=>!p.ground&&x>p.x+20&&x<p.x+p.w-20);spawnEnemy(type,x,plat&&i%2?plat.y:650);});if(index===0){G.enemies.forEach(e=>e.hp=e.maxHp=Math.round(e.hp*.85));}G.doors=[{x:G.world-240,y:650,type:'smile',label:'미소 · 주민의 힘'},{x:G.world-90,y:650,type:pick(['gold','heal','weapon']),label:''}];}else if(index===6){G.npcs=[{x:770,y:650,type:'merchant',name:'떠돌이 상인'}];G.doors=[{x:1410,y:650,type:'boss',label:'브락의 갑판'}];G.cleared=true;}else{G.platforms.push({x:350,y:510,w:230,h:25},{x:1290,y:510,w:230,h:25});G.boss=spawnEnemy('boss',1250,650);G.doors=[];}
if(index===3)G.enemies.find(e=>e.type==='elite').name='악명 높은 갈고리 잭';G.p.y=600;G.run.hp=clamp(G.run.hp+meta.upgrades.flask*2,0,G.run.maxHp);G.banner={title:index===7?'깡패 선장 브락':index===6?'폭풍 전, 한 잔':index===3?'갈고리 잭의 소굴':ROOM_NAMES[G.layout],sub:index===7?'BOSS · THE CAPTAIN OF EMPTY THREATS':`달빛 부두 · ${index+1} / 8`,time:3};$('#hud').hidden=false;updateHUD();if(index===0)toast('J 공격 · K 구르기 · 적의 금빛 반짝임에 L 받아치기');}
const ROOM_NAMES=['밀물의 잔교','밧줄꾼의 망루','푸른 현상 동굴','등불 아래의 결투','밀수꾼의 숨은 길','소금 묻은 계단','버려진 닻의 정박지','갈매기의 지붕길','술통이 구르는 부두','밤바람의 사다리','울음 없는 만조','떠돌이의 낡은 갑판'];
let eid=0;function spawnEnemy(type,x,y){const stats={sailor:[68,13,90],crab:[46,10,125],rope:[58,11,75],elite:[200,19,95],boss:[880,22,120]}[type];let e={id:++eid,type,x,y,vx:0,vy:0,w:type==='boss'?64:type==='crab'?48:38,h:type==='crab'?32:type==='boss'?112:77,hp:stats[0],maxHp:stats[0],damage:stats[1],speed:stats[2],face:-1,state:'idle',timer:rand(.5,1.3),windup:0,attack:0,cooldown:rand(.6,1.8),stun:0,hurt:0,poison:0,poisonTick:0,ground:false,walk:rand(0,6),taunt:'',tauntTime:0,phase:1,pattern:0,hit:false,dead:0};G.enemies.push(e);return e;}
function has(id){return G.run?.boons.includes(id);}
function addLaugh(n){if(G.run)G.run.laugh=clamp(G.run.laugh+n,0,100);}
function toast(s,time=3){$('#toast').textContent=s;$('#toast').classList.add('visible');G.toastTime=time;}
function audioStart(){if(!meta.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();}catch(e){}}
function tone(freq,dur=.15,type='sine',vol=.06,slide=1){if(!meta.sound||!audioCtx)return;let o=audioCtx.createOscillator(),v=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq*slide),audioCtx.currentTime+dur);v.gain.setValueAtTime(vol,audioCtx.currentTime);v.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(v);v.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}
function noise(dur=.09,vol=.08){if(!meta.sound||!audioCtx)return;let b=audioCtx.createBuffer(1,audioCtx.sampleRate*dur,audioCtx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*(1-i/a.length);let s=audioCtx.createBufferSource(),v=audioCtx.createGain();s.buffer=b;v.gain.value=vol;s.connect(v);v.connect(audioCtx.destination);s.start();}
function sfx(type){if(type==='slash'){noise(.1,.07);tone(350,.1,'triangle',.025,.25);}if(type==='hit'){noise(.07,.14);tone(100,.13,'triangle',.08,.4);}if(type==='parry'){[587,880,1174].forEach((f,i)=>tone(f,.3+i*.07,'sine',.045));noise(.055,.05);}if(type==='jump')tone(180,.15,'sine',.035,2);if(type==='dash')noise(.2,.055);if(type==='coin'){tone(988,.1,'sine',.035);tone(1318,.2,'sine',.02);}if(type==='chicken'){tone(390,.16,'square',.022,.7);tone(570,.22,'triangle',.035,.3);}if(type==='bomb'){noise(.3,.13);tone(70,.35,'triangle',.1,.3);}if(type==='ult'){[196,294,392,587].forEach(f=>tone(f,.8,'triangle',.035));}if(type==='hurt'){noise(.13,.07);tone(160,.2,'sawtooth',.025,.3);}}
function music(dt){if(!meta.sound||!audioCtx||G.mode==='paused')return;musicClock-=dt;if(musicClock>0)return;musicClock=.33;let melody=[196,0,294,247,220,0,330,294,196,247,294,392,330,294,247,0],f=melody[musicTick%16];if(f)tone(f,.42,'triangle',.012);if(musicTick%4===0)tone([98,110,82.41,73.42][Math.floor(musicTick/4)%4],.8,'sine',.035);if(G.mode==='play'&&musicTick%2===0)noise(.035,.014);musicTick++;}
function pollPad(){let pads=navigator.getGamepads?.()||[],pad=Array.from(pads).find(Boolean);if(!pad){lastPad={};return;}let map={left:(pad.axes[0]||0)<-.25,right:(pad.axes[0]||0)>.25,up:pad.axes[1]<-.4,down:pad.axes[1]>.4,jump:pad.buttons[0]?.pressed,attack:pad.buttons[2]?.pressed,dash:pad.buttons[1]?.pressed,parry:pad.buttons[5]?.pressed,skillU:pad.buttons[6]?.pressed,skillI:pad.buttons[7]?.pressed,ult:pad.buttons[3]?.pressed,interact:pad.buttons[4]?.pressed,pause:pad.buttons[9]?.pressed};for(let [key,v] of Object.entries(map)){if(v){inputDevice='gamepad';keys.add('pad:'+key);if(!lastPad[key])pressed.add(key);}else keys.delete('pad:'+key);}lastPad=map;}
const KEYMAP={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',Space:'jump',KeyJ:'attack',KeyK:'dash',KeyL:'parry',KeyU:'skillU',KeyI:'skillI',KeyO:'ult',KeyE:'interact',Escape:'pause'};
function down(action){return keys.has('pad:'+action)||Object.entries(KEYMAP).some(([code,a])=>a===action&&keys.has(code));}
function tap(action){return pressed.has(action);}
window.addEventListener('keydown',e=>{if(!['play','hub'].includes(G.mode)&&e.code!=='Escape'){if(G.mode==='title'&&e.code==='Enter'&&e.target.tagName!=='BUTTON'){audioStart();hub();}return;}let a=KEYMAP[e.code];if(a){e.preventDefault();inputDevice='keyboard';if(!e.repeat)pressed.add(a);keys.add(e.code);}if(e.code==='Enter'&&G.mode==='title'){audioStart();hub();}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pressed.clear();if(['play','hub'].includes(G.mode))pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['play','hub'].includes(G.mode))pause();});
function particle(x,y,color,n=12,speed=140,size=3,gravity=350){for(let i=0;i<n;i++){let a=rand(-Math.PI,Math.PI),v=rand(speed*.25,speed);G.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,color,size:rand(size*.5,size*1.5),life:rand(.25,.7),max:.7,g:gravity});}if(G.particles.length>500)G.particles.splice(0,G.particles.length-500);}
function textAt(text,x,y,color='#ffdb94',size=19){G.texts.push({text,x,y,vy:-35,time:1,max:1,color,size});}
function shake(amount=7){if(!meta.reduced)G.shake=Math.max(G.shake,amount);}
function damageEnemy(e,damage,knock=100,parried=false){if(e.hp<=0)return;e.hp-=damage;e.hurt=.16;e.vx=G.p.face*knock;if(e.type!=='boss'){if(parried||!['windup','attack'].includes(e.state))e.stun=Math.max(e.stun,parried?1.3:.10);e.vy=-60;}else if(parried)e.stun=1.1;if(has('poison')&&!parried)e.poison=3;particle(e.x,e.y-e.h*.5,parried?'#c6fcf6':'#ffd69c',parried?27:12,parried?360:200,3);textAt(Math.round(damage),e.x+rand(-12,12),e.y-e.h-5,parried?'#b4fff0':'#ffddb3',parried?28:18);G.hitstop=parried?.085:.045;shake(parried?11:4);sfx(parried?'parry':'hit');if(e.hp<=0)killEnemy(e);}
function killEnemy(e){e.hp=0;e.dead=.65;e.state='dead';G.run.kills++;addLaugh(6);for(let i=0;i<(e.type==='boss'?18:e.type==='elite'?8:3);i++)G.drops.push({x:e.x,y:e.y-30,vx:rand(-180,180),vy:rand(-340,-140),type:'coin',t:0});if(Math.random()<.25||e.type==='boss'||e.type==='elite'){meta.film+=e.type==='boss'?3:1;G.run.filmGained+=e.type==='boss'?3:1;textAt('필름 +'+(e.type==='boss'?3:1),e.x,e.y-e.h-45,'#a0dbef',16);}if(e.type==='elite'||e.type==='boss'){let n=e.type==='boss'?5:2;meta.teeth+=n;G.run.teethGained+=n;textAt('금니 +'+n,e.x,e.y-e.h-75,'#f5cd78',20);}save();if(e.type==='boss'){G.clearTimer=2.7;G.cleared=true;G.flash=.4;G.banner={title:'허풍도 끝이 나는 법.',sub:'깡패 선장 브락 · 격파',time:3};sfx('ult');}}
function hurtPlayer(damage,source){let p=G.p;if(p.invul>0||p.dash>0||G.mode!=='play')return;if(p.parry>0&&source){parrySuccess(source);return;}G.run.hp=Math.max(0,G.run.hp-damage);p.hurt=.32;p.invul=.85;p.vx=(source&&source.x<p.x?1:-1)*300;p.vy=-160;addLaugh(-12);shake(11);G.flash=.15;G.hitstop=.06;particle(p.x,p.y-40,'#e59186',14,180);textAt('-'+damage,p.x,p.y-90,'#ff9c93',23);sfx('hurt');if(G.run.hp<=0){if(has('secondlife')&&!G.run.revived){G.run.revived=true;G.run.hp=Math.ceil(G.run.maxHp*.35);p.invul=2;toast('로사의 외상: “아직 계산 안 했잖아!”');particle(p.x,p.y-40,'#96f0c0',40,270);sfx('parry');}else die();}}
function parrySuccess(e){G.p.parry=0;G.p.invul=.45;e.attack=0;e.windup=0;e.state='stun';e.stun=has('stunparry')?2.3:1.3;e.cooldown=1.1;let damage=(G.run.weapon==='sword'?38:30)+(has('stunparry')?12:0);damageEnemy(e,damage,420,true);G.run.parries++;addLaugh(24);if(has('healparry'))G.run.hp=Math.min(G.run.maxHp,G.run.hp+5);G.slashes.push({x:G.p.x+G.p.face*50,y:G.p.y-45,face:G.p.face,combo:2,time:.32,max:.32,parry:true});textAt(pick(['입만 일등 항해사!','거울부터 보고 와!','네 허풍은 만선이네!']),G.p.x,G.p.y-125,'#bbfff0',21);}
function doAttack(){let p=G.p;if(p.attackCD>0||p.dash>0||p.hurt>0)return;if(p.comboTimer<=0)p.combo=0;else p.combo=(p.combo+1)%3;p.comboTimer=.82;let flail=G.run?.weapon==='flail';p.attack=flail?.4:.28;p.attackCD=flail?.39:.25;p.hitIds.clear();let reach=flail?170:p.combo===2?147:112;G.slashes.push({x:p.x+p.face*48,y:p.y-42,face:p.face,combo:p.combo,time:flail?.35:.24,max:flail?.35:.24,flail});p.vx=p.face*(p.combo===2?220:105);sfx('slash');if(G.mode==='play'){for(let e of G.enemies){if(e.hp<=0)continue;let dx=(e.x-p.x)*p.face,dy=Math.abs((e.y-e.h*.45)-(p.y-40));if(dx>-22&&dx<reach+e.w*.5&&dy<80){let damage=(flail?[21,25,38]:[17,20,30])[p.combo];damageEnemy(e,damage,p.combo===2?320:130);p.hitIds.add(e.id);addLaugh(flail?7:4);if(has('slip')&&p.combo===2){e.stun=Math.max(e.stun,1.4);e.vx=p.face*500;}}}}}
function useSkill(which){let p=G.p;if(G.mode!=='play')return;if(which==='U'&&p.skillU<=0){p.skillU=has('chicken')?4:6;for(let e of G.enemies)if(e.hp>0&&Math.abs(e.x-p.x)<220&&Math.abs(e.y-p.y)<140){damageEnemy(e,has('chicken')?34:18,380);e.stun=Math.max(e.stun,.75);}addLaugh(14);G.slashes.push({x:p.x,y:p.y-45,time:.5,max:.5,chicken:true,face:p.face});particle(p.x,p.y-40,'#f0cf67',30,350,5);textAt('꽥! 말이 너무 많아!',p.x,p.y-100,'#ffe9a9',19);sfx('chicken');}if(which==='I'&&p.skillI<=0){p.skillI=8;G.projectiles.push({x:p.x+p.face*25,y:p.y-57,vx:p.face*520,vy:-390,type:'bomb',time:1.2,owner:'hero'});sfx('slash');}}
function ultimate(){if(G.mode!=='play'||G.run.laugh<100)return;G.run.laugh=0;G.p.invul=1.4;let damage=72+(has('radiance')?40:0);for(let e of G.enemies)if(e.hp>0&&Math.abs(e.x-G.p.x)<1200){damageEnemy(e,damage,500,true);e.stun=Math.max(e.stun,2);}G.flash=.7;shake(20);G.hitstop=.12;particle(G.p.x,G.p.y-45,'#ffd991',85,850,6,0);G.banner={title:'네 허풍에 돛을 달면 세계 일주도 하겠어!',sub:'필살 대사 · 관중 대폭소',time:2.5};sfx('ult');}
function physics(a,dt){const oldY=a.y;a.vy+=1650*dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.ground=false;if(a.vy>=0){for(let p of G.platforms){if(a.x+a.w*.4>p.x&&a.x-a.w*.4<p.x+p.w&&oldY<=p.y+8&&a.y>=p.y){a.y=p.y;a.vy=0;a.ground=true;break;}}}a.x=clamp(a.x,25,G.world-25);}
function updatePlayer(dt){let p=G.p;for(let k of ['attack','attackCD','comboTimer','dashCD','parry','parryCD','hurt','invul','skillU','skillI','jumpBuffer'])p[k]=Math.max(0,p[k]-dt);if(p.ground){p.coyote=.12;p.jumps=0;}else p.coyote=Math.max(0,p.coyote-dt);if(tap('jump'))p.jumpBuffer=.12;let direction=(down('right')?1:0)-(down('left')?1:0);if(direction)p.face=direction;
if(p.rope){p.vx=0;p.vy=0;p.y=clamp(p.y+((down('down')?1:0)-(down('up')?1:0))*230*dt,p.rope.y+40,p.rope.bottom);p.x=p.rope.x;if(tap('jump')||direction){p.rope=null;p.vy=-590;p.vx=direction*300;p.jumps=1;p.jumpBuffer=0;p.ropeCD=.35;}}else{p.ropeCD=Math.max(0,(p.ropeCD||0)-dt);if(down('up')&&!p.ropeCD){let rope=G.ropes.find(r=>Math.abs(r.x-p.x)<32&&p.y>r.y&&p.y-p.h<r.bottom);if(rope)p.rope=rope;}if(p.dash>0){p.dash-=dt;p.vx=p.face*770;p.vy=0;p.trail-=dt;if(p.trail<=0){p.trail=.035;G.ghosts.push({x:p.x,y:p.y,face:p.face,time:.22,walk:p.walk});}if(p.dash<=0&&has('dashlight')){particle(p.x,p.y-35,'#a9faff',25,300);for(let e of G.enemies)if(e.hp>0&&Math.abs(e.x-p.x)<155){e.stun=Math.max(e.stun,1);e.state='stun';}}}else if(p.hurt<=0){let speed=p.attack>0?140:320;p.vx=lerp(p.vx,direction*speed,Math.min(1,dt*(p.ground?16:9)));if(p.jumpBuffer>0&&(p.ground||p.coyote>0||p.jumps<2)){if(!p.ground&&p.coyote<=0)p.jumps=Math.max(p.jumps,1);p.jumps++;p.vy=p.jumps===1?-625:-570;p.ground=false;p.coyote=0;p.jumpBuffer=0;particle(p.x,p.y,'#bbd5d1',p.jumps===2?17:9,125,3,200);sfx('jump');}if(tap('dash')&&p.dashCD<=0){p.dash=.25;p.dashCD=.72;p.invul=.32;p.vy=0;particle(p.x,p.y-15,'#b5ded7',10,100);sfx('dash');}if(tap('parry')&&p.parryCD<=0){p.parry=.30+meta.upgrades.parry*.025;p.parryCD=.68;p.attack=0;tone(520,.08,'sine',.035);}
if(tap('attack')){if(p.attackCD>.03)p.queued=true;else doAttack();}if(p.queued&&p.attackCD<=0){p.queued=false;doAttack();}if(tap('skillU'))useSkill('U');if(tap('skillI'))useSkill('I');if(tap('ult'))ultimate();}else p.vx*=Math.pow(.08,dt);physics(p,dt);}
p.walk+=Math.abs(p.vx)*dt*.035;if(p.ground&&Math.abs(p.vx)>170&&Math.random()<.25)particle(p.x,p.y,'#9cafa866',1,35,2,20);if(p.y>850){p.x=150;p.y=500;p.vy=0;if(G.mode==='play')hurtPlayer(12,null);}if(tap('interact'))interact();}
const TAUNTS=['네 칼은 버터도 못 자르겠어!','도망도 기술이라더라!','그 얼굴로 해적을 한다고?','네 허풍에 배가 뜨겠구나!'];
function beginWindup(e){e.state='windup';e.windup=e.type==='boss'?(e.phase===2?.62:.85):e.type==='crab'?.56:.76;e.timer=e.windup;e.face=G.p.x>e.x?1:-1;e.taunt=e.type==='crab'?'딱! 딱! (겁났게?)':pick(TAUNTS);e.tauntTime=e.windup+1;e.hit=false;e.pattern=e.type==='boss'?(e.pattern+1)%3:0;}
function updateEnemy(e,dt){if(e.hp<=0){e.dead=Math.max(0,e.dead-dt);return;}e.hurt=Math.max(0,e.hurt-dt);e.tauntTime=Math.max(0,e.tauntTime-dt);if(e.poison>0){e.poison-=dt;e.poisonTick-=dt;if(e.poisonTick<=0){e.poisonTick=1;let damage=has('stunparry')&&e.stun>0?15:5;e.hp-=damage;particle(e.x,e.y-35,'#9bc579',4,50,3);textAt(damage,e.x,e.y-80,'#b7de8b',14);if(e.hp<=0){killEnemy(e);return;}}}if(e.type==='boss'&&e.hp<e.maxHp*.5&&e.phase===1){e.phase=2;e.taunt='좋아, 이제 진짜 선장처럼 굴어 주지!';e.tauntTime=3;shake(8);particle(e.x,e.y-50,'#eeb878',30,250);}
if(e.stun>0){e.stun-=dt;e.state='stun';e.vx*=Math.pow(.03,dt);if(e.stun<=0){e.state='idle';e.cooldown=.12;}physics(e,dt);return;}
let dx=G.p.x-e.x,dy=Math.abs(G.p.y-e.y),dist=Math.abs(dx);if(e.state==='windup'){e.timer-=dt;e.vx*=Math.pow(.001,dt);if(e.timer<=0){e.state='attack';e.attack=e.type==='boss'&&e.pattern===1?.55:.23;e.vx=e.face*(e.type==='crab'?430:e.type==='boss'&&e.pattern===1?610:180);G.slashes.push({x:e.x+e.face*45,y:e.y-e.h*.5,face:e.face,combo:e.type==='boss'?2:0,time:.28,max:.28,enemy:true});if(e.type==='boss'&&e.pattern===2){for(let side of [-1,1])G.projectiles.push({x:e.x+side*60,y:620,vx:side*370,vy:0,type:'wave',time:2,owner:'enemy',source:e});shake(7);}if(e.type==='rope'){G.projectiles.push({x:e.x,y:e.y-55,vx:e.face*410,vy:-40,type:'hook',time:2.5,owner:'enemy',source:e});e.hit=true;}sfx('slash');}}else if(e.state==='attack'){e.attack-=dt;let reach=e.type==='boss'?(e.pattern===2?190:145):e.type==='crab'?65:100;if(!e.hit&&dist<reach&&dy<100&&(dx*e.face>-20)){e.hit=true;hurtPlayer(e.damage+(e.type==='boss'&&e.phase===2?3:0),e);}if(e.attack<=0){e.state='idle';e.cooldown=e.type==='boss'?(e.phase===2?.75:1.1):rand(1.05,1.8);e.vx=0;}}else{e.cooldown-=dt;e.face=dx>0?1:-1;let range=e.type==='rope'?420:e.type==='boss'?185:90;if(dist<range&&dy<100&&e.cooldown<=0)beginWindup(e);else if(dist>range*.8&&dist<900){e.vx=e.face*e.speed;if(e.ground&&G.p.y<e.y-90&&dist<420){e.vy=-590;}if(e.ground&&G.p.y>e.y+80){e.y+=12;}}else e.vx*=Math.pow(.01,dt);}
e.walk+=Math.abs(e.vx)*dt*.03;physics(e,dt);}
function explode(p){particle(p.x,p.y,'#f9c67a',42,410,5);G.slashes.push({x:p.x,y:p.y,time:.45,max:.45,blast:true});shake(9);sfx('bomb');for(let e of G.enemies)if(e.hp>0&&Math.hypot(e.x-p.x,e.y-e.h*.5-p.y)<210){damageEnemy(e,40,400);e.stun=Math.max(e.stun,.8);}}
function updateProjectiles(dt){for(let p of G.projectiles){p.time-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.type==='bomb'){p.vy+=880*dt;if(p.time<=0||p.y>=635){explode(p);p.remove=true;}}else{let hero=G.p;if(Math.abs(p.x-hero.x)<35&&Math.abs(p.y-(hero.y-40))<48){hurtPlayer(12,p.source);p.remove=true;}if(p.time<=0||p.x<0||p.x>G.world)p.remove=true;}}G.projectiles=G.projectiles.filter(p=>!p.remove);}
function updateDrops(dt){for(let d of G.drops){d.t+=dt;d.vy+=800*dt;d.x+=d.vx*dt;d.y+=d.vy*dt;if(d.y>638){d.y=638;d.vy=-Math.abs(d.vy)*.35;d.vx*=.7;}let dx=G.p.x-d.x,dy=G.p.y-35-d.y;if(d.t>.3&&Math.hypot(dx,dy)<210){d.x+=dx*dt*9;d.y+=dy*dt*9;if(Math.hypot(dx,dy)<35){d.remove=true;G.run.gold+=3;sfx('coin');particle(d.x,d.y,'#f9cd76',3,60,2);}}if(d.t>15){G.run.gold+=3;d.remove=true;}}G.drops=G.drops.filter(d=>!d.remove);}
function updateEffects(dt){for(let p of G.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.g*dt;p.vx*=1-dt*.8;}G.particles=G.particles.filter(p=>p.life>0);for(let f of G.texts){f.time-=dt;f.y+=f.vy*dt;}G.texts=G.texts.filter(f=>f.time>0);for(let s of G.slashes)s.time-=dt;G.slashes=G.slashes.filter(s=>s.time>0);for(let gh of G.ghosts)gh.time-=dt;G.ghosts=G.ghosts.filter(gh=>gh.time>0);G.shake=Math.max(0,G.shake-dt*30);G.flash=Math.max(0,G.flash-dt*2);if(G.banner){G.banner.time-=dt;if(G.banner.time<=0)G.banner=null;}if(G.toastTime>0){G.toastTime-=dt;if(G.toastTime<=0)$('#toast').classList.remove('visible');}}
function menuPad(){if(inputDevice!=='gamepad'||!$('#overlay').classList.contains('open'))return;const items=[...$('#overlay').querySelectorAll('button:not(:disabled)')];if(!items.length)return;let index=items.indexOf(document.activeElement);if(tap('left')||tap('up'))items[(index-1+items.length)%items.length].focus();if(tap('right')||tap('down'))items[(index+1)%items.length].focus();if(tap('jump'))(items[index]||items[0]).click();}
function update(dt){G.t+=dt;pollPad();if(tap('pause')){if(G.mode==='paused'||G.mode==='dialog')resume();else if(['hub','play'].includes(G.mode))pause();}if(!['play','hub'].includes(G.mode)){menuPad();}if(!['hub','play','title'].includes(G.mode)){pressed.clear();return;}music(dt);updateEffects(dt);if(G.mode==='title'){pressed.clear();return;}if(G.hitstop>0){G.hitstop-=dt;pressed.clear();return;}if(G.run)G.run.time+=dt;updatePlayer(dt);if(G.mode==='play'){for(let e of G.enemies)updateEnemy(e,dt);updateProjectiles(dt);updateDrops(dt);if(!G.cleared&&G.enemies.length&&G.enemies.every(e=>e.hp<=0)){G.cleared=true;G.clearTimer=.9;G.banner={title:G.room===3?'갈고리도 말발 앞엔 무뎌진다.':'되찾은 밤, 하나의 미소.',sub:'ROOM CLEAR · 다음 문을 선택하세요',time:2.3};if(G.room===1&&!meta.clues.includes('tooth')){meta.clues.push('tooth');save();toast('단서 획득 · 금니에 새겨진 D.P.');}}if(G.cleared&&G.clearTimer>0){G.clearTimer-=dt;if(G.clearTimer<=0&&G.room===7){victory();}}}G.camera=lerp(G.camera,clamp(G.p.x-W*.39,0,G.world-W),Math.min(1,dt*5));updatePrompt();updateHUD();pressed.clear();}
function updatePrompt(){let near=G.npcs.find(n=>Math.abs(n.x-G.p.x)<100&&Math.abs(n.y-G.p.y)<100);let door=G.doors.find(d=>Math.abs(d.x-G.p.x)<80&&Math.abs(d.y-G.p.y)<100);let text='';if(near)text=`${inputDevice==='gamepad'?'LB':'E'} · ${near.name}와 대화`;else if(door){if(G.mode==='hub'||G.cleared)text=`${inputDevice==='gamepad'?'LB':'E'} · ${door.label||rewardName(door.type)}`;else text='적을 모두 물리치면 문이 열립니다.';}else if(G.p.rope)text='↑ ↓ 밧줄 오르기 · Space 뛰어내리기';else if(G.ropes.some(r=>Math.abs(r.x-G.p.x)<35&&G.p.y>r.y&&G.p.y-G.p.h<r.bottom))text='↑ 밧줄 잡기';G.prompt=text;$('#prompt').textContent=text;$('#prompt').style.display=text?'block':'none';}
function rewardName(t){return ({smile:'주민의 미소',gold:'금화 주머니',heal:'따뜻한 럼차',weapon:'무기 보관함',boss:'깡패 선장의 갑판',depart:'달빛 부두로 출항'})[t]||t;}
function interact(){let n=G.npcs.find(n=>Math.abs(n.x-G.p.x)<100&&Math.abs(n.y-G.p.y)<100);if(n){npcTalk(n.type);return;}let d=G.doors.find(d=>Math.abs(d.x-G.p.x)<85&&Math.abs(d.y-G.p.y)<100);if(!d||!(G.mode==='hub'||G.cleared))return;if(d.type==='depart'){newRun();return;}if(d.type==='boss'){loadRoom(7);return;}G.run.reward=d.type;if(d.type==='smile')chooseBoon();else if(d.type==='weapon')weaponReward();else if(d.type==='gold'){G.run.gold+=45;toast('금화 45 획득');loadRoom(G.room+1);}else if(d.type==='heal'){let n=30+meta.upgrades.flask*5;G.run.hp=Math.min(G.run.maxHp,G.run.hp+n);loadRoom(G.room+1);toast('따뜻한 럼차 · 체면 '+n+' 회복');}}
function updateHUD(){let r=G.run;$('#depart-shortcut').hidden=!!r;let hp=r?r.hp:100+meta.upgrades.health*12,max=r?r.maxHp:hp;$('#health-fill').style.width=hp/max*100+'%';$('#health-text').textContent=`${Math.ceil(hp)} / ${max}`;$('#laugh-fill').style.width=(r?r.laugh:0)+'%';$('#laugh-text').textContent=(r?Math.floor(r.laugh):0)+'%';$('#area-label').textContent=G.mode==='hub'?'밤의 갈매기 · 출항 준비':G.room===7?'브락의 갑판':G.room===6?'떠돌이의 정박지':'달빛 부두 · '+ROOM_NAMES[G.layout];$('#room-objective').textContent=r?(G.cleared?'문을 골라 다음 방으로 →':'남은 적 '+G.enemies.filter(e=>e.hp>0).length):'주민과 대화하거나 출항하세요';$('#room-dots').textContent=r?Array.from({length:8},(_,i)=>i<G.room?'◆':i===G.room?'◇':'·').join(' '):'HOME · MOONLIT HARBOR';$('#currency').textContent=r?'◈ '+r.gold:'금니 '+meta.teeth+' · 필름 '+meta.film;$('#weapon-name').textContent=r&&r.weapon==='flail'?'고무 닭 플레일':'녹슨 커틀러스';$('#boon-count').textContent=r?'되찾은 미소 '+r.boons.length:'E · 주민과 대화하기';for(let [id,v] of [['chicken',G.p?.skillU||0],['bomb',G.p?.skillI||0]]){let el=$('#skill-'+id);el.classList.toggle('cooldown',v>0);el.querySelector('b').textContent=v>0?v.toFixed(1)+'초':'준비';}$('#skill-ult b').textContent=r&&r.laugh>=100?'준비 완료':(r?Math.floor(r.laugh):0)+'%';$('#skill-ult').classList.toggle('ready',r&&r.laugh>=100);$('#boss-hud').hidden=!(G.boss&&G.boss.hp>0);if(G.boss){$('#boss-fill').style.width=Math.max(0,G.boss.hp/G.boss.maxHp*100)+'%';$('#boss-name').textContent=G.boss.phase===2?'브락 · 허풍이 벗겨진 선장':'깡패 선장 브락';}}
// Drawing helpers and a small two-bone animation rig. World coordinates stay in CSS-independent units.
function poly(points,fill,stroke=null,width=2){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function line(points,color,width=2){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();}
function ellipse(x,y,rx,ry,color){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function label(text,x,y,size=14,color='#e9dfc4',align='center'){ctx.font=`600 ${size}px ${FONT}`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillStyle=color;ctx.fillText(text,x,y);}
function glow(x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
function lantern(x,y,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);let f=.8+Math.sin(G.t*5+x)*.08;glow(0,0,95,`rgba(248,173,83,${.17*f})`);line([[0,-38],[0,-20]],'#1b2834',3);poly([[-11,-18],[11,-18],[14,17],[-14,17]],'#16232d','#071220',3);ctx.fillStyle='#f2c277';ctx.fillRect(-8,-14,16,27);line([[0,-15],[0,14]],'#364044',2);ellipse(0,1,4,8,'#ffecba');poly([[-17,-19],[0,-29],[17,-19]],'#24323b','#0b192a',2);poly([[-17,17],[17,17],[10,23],[-10,23]],'#162330');ctx.restore();}
function barrel(x,y,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);poly([[-24,0],[-28,-15],[-28,-50],[-21,-65],[21,-65],[28,-50],[28,-15],[24,0]],'#5a4540','#101c2b',3);for(let i=-16;i<=16;i+=11)line([[i,0],[i*1.12,-32],[i,-63]],'#7f6050',2);roundRect(-28,-49,56,7,1,'#28383e');roundRect(-28,-16,56,7,1,'#28383e');ellipse(0,-64,21,5,'#826048');ctx.restore();}
function crate(x,y,s=54){ctx.fillStyle='#56483d';ctx.fillRect(x-s/2,y-s,s,s);ctx.strokeStyle='#172536';ctx.lineWidth=4;ctx.strokeRect(x-s/2,y-s,s,s);line([[x-s/2+6,y-6],[x+s/2-6,y-s+6]],'#8a6950',7);line([[x-s/2+6,y-s+6],[x+s/2-6,y-6]],'#8a6950',6);line([[x-s/2+2,y-s],[x+s/2-2,y-s]],'#bf9765',2);}
function drawBackdrop(){const title=G.mode==='title',cam=title?Math.sin(G.t*.035)*90:G.camera;ctx.fillStyle='#111f36';ctx.fillRect(0,0,W,H);if(BG.complete&&BG.naturalWidth){const iw=1900,ih=iw/BG.naturalWidth*BG.naturalHeight;ctx.drawImage(BG,-170-cam*.10,-Math.max(0,ih-H)*.45,iw,ih);}else{const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#0c1532');grad.addColorStop(1,'#315269');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ellipse(1120,140,68,68,'#dfe5c8');}
let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#07122438');g.addColorStop(.55,'#07122400');g.addColorStop(1,'#071224dd');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
for(let i=0;i<36;i++){let y=585+i*5,x=((i*167-G.t*(8+i%4)*2-cam*.18)%1600+1600)%1600-70;line([[x,y],[x+25+i%5*13,y]],i%6===0?'#b2cdd125':'#a8d4d50d',1.5);}
for(let i=0;i<5;i++){let x=((G.t*(5+i)+i*410-cam*.12)%1900)-230,y=370+i*49;glow(x,y,210,'#a4d8eb08');}
if(title){g=ctx.createLinearGradient(0,0,W,0);g.addColorStop(0,'#061121bd');g.addColorStop(.6,'#07152411');g.addColorStop(1,'#07152400');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);return;}
// Midground timber masts and gently moving rigging, slower than the gameplay plane.
ctx.save();ctx.translate(-cam*.4,0);for(let i=0;i<7;i++){let x=i*470+120;line([[x,720],[x+13,230]],'#122437',9);line([[x+11,264],[x+172,550],[x-72,530]],'#25384a88',2);poly([[x+12,260],[x+147,325+Math.sin(G.t+i)*4],[x+15,449]],'#1d344888');line([[x+15,289],[x-150,415]],'#152a3a',3);}ctx.restore();}
function drawPlatform(p){if(p.ground){const g=ctx.createLinearGradient(0,p.y,0,800);g.addColorStop(0,G.room===7?'#665145':'#49504b');g.addColorStop(.25,'#233039');g.addColorStop(1,'#081522');ctx.fillStyle=g;ctx.fillRect(p.x,p.y,p.w,170);line([[p.x,p.y],[p.x+p.w,p.y]],'#c3a170',5);line([[p.x,p.y+8],[p.x+p.w,p.y+8]],'#777565',3);for(let x=p.x;x<p.x+p.w;x+=66){line([[x,p.y+9],[x-17,p.y+170]],'#0b1927aa',3);line([[x+5,p.y+12],[x+45,p.y+12]],'#a49a711f',2);if(x%132===0){ellipse(x+10,p.y+18,2,2,'#bec2a17a');ellipse(x+10,p.y+28,2,2,'#101a23');}}for(let x=p.x+70;x<p.x+p.w;x+=280){ctx.fillStyle='#152734';ctx.fillRect(x,p.y+23,20,145);line([[x-35,p.y+28],[x+18,p.y+90],[x+68,p.y+28]],'#1a2b33',11);line([[x,p.y+26],[x,p.y+160]],'#5b635944',3);}}else{ctx.fillStyle='#394648';ctx.fillRect(p.x,p.y,p.w,p.h);line([[p.x,p.y],[p.x+p.w,p.y]],'#c0a674',5);line([[p.x,p.y+6],[p.x+p.w,p.y+6]],'#6a7566',2);line([[p.x,p.y+23],[p.x+p.w,p.y+23]],'#172936',5);for(let x=p.x+8;x<p.x+p.w;x+=34){line([[x,p.y+4],[x,p.y+20]],'#172d37',2);ellipse(x+5,p.y+9,1.4,1.4,'#c0ac79');}line([[p.x+25,p.y+24],[p.x+75,p.y+90],[p.x+75,p.y+24]],'#23333b',8);line([[p.x+p.w-25,p.y+24],[p.x+p.w-75,p.y+90],[p.x+p.w-75,p.y+24]],'#23333b',8);for(let x of [p.x+18,p.x+p.w-18]){line([[x,p.y],[x,p.y-43]],'#435155',6);}ctx.beginPath();ctx.moveTo(p.x+18,p.y-42);ctx.quadraticCurveTo(p.x+p.w/2,p.y-12,p.x+p.w-18,p.y-42);ctx.strokeStyle='#b3a98477';ctx.lineWidth=2;ctx.stroke();}}
function drawHouse(x,y,w,h,name,lit=true){ctx.save();ctx.translate(x,y);poly([[-w/2,0],[-w/2,-h],[0,-h-76],[w/2,-h],[w/2,0]],'#273642','#0a1829',7);poly([[-w/2-22,-h+6],[0,-h-86],[w/2+25,-h+6]],'#253149','#102135',6);for(let j=0;j<4;j++)line([[-w/2+8,-h+j*h/4],[w/2-8,-h+j*h/4]],'#3a4a52',3);line([[-w/2+20,0],[-w/2+20,-h]],'#152433',12);line([[w/2-20,0],[w/2-20,-h]],'#152433',12);line([[0,-h-62],[0,-h+4]],'#526065',5);roundRect(-31,-91,62,91,20,'#0b1829','#85725c');for(let side of [-1,1]){let wx=side*w*.29;roundRect(wx-24,-h+34,48,64,3,lit?'#d4aa69':'#142737','#1a2a39');if(lit)glow(wx,-h+64,65,'#efb65522');line([[wx,-h+35],[wx,-h+97]],'#2b3a42',4);line([[wx-23,-h+63],[wx+23,-h+63]],'#2b3a42',4);}if(name){roundRect(-100,-h-15,200,36,3,'#433e39','#c8a66d');label(name,0,-h+3,17,'#f1d9ac');}lantern(w/2-25,-115,.75);ctx.restore();}
function drawShip(){ctx.save();ctx.translate(950,650);line([[0,20],[0,-560]],'#172937',23);line([[-10,-540],[-480,30]],'#a5a89444',2);line([[10,-540],[570,20]],'#a5a89444',2);line([[-220,-440],[260,-440]],'#2b3c46',10);poly([[-202,-429],[235,-429],[215+Math.sin(G.t)*5,-175],[100,-185],[-40,-168],[-187,-186]],'#78838638','#31455366',3);label('⚓',15,-310,100,'#10243688');for(let i=0;i<7;i++)line([[110+i*35,-530+i*59],[170+i*35,-530+i*59]],'#626f7755',2);line([[-630,-60],[-300,-90],[0,-60],[340,-85],[670,-60]],'#77847d88',3);ctx.restore();}
function drawEnvironment(){if(G.worldMode==='hub'){drawHouse(420,650,390,218,'밤의 갈매기',true);drawHouse(965,650,260,174,'등대지기의 공방',meta.upgrades.health>0||meta.residents.includes('등대지기 노아'));drawHouse(1340,650,235,152,'미소의 대장간',meta.residents.includes('생선 장수 마리'));}else if(G.room===7)drawShip();else if(G.room===6){drawHouse(780,650,380,160,'뭐든 파는 마리',true);}else{for(let i=0;i<9;i++){let x=220+i*310;if(i%2===0){line([[x,650],[x,425]],'#1c303c',10);line([[x-3,430],[x+43,430]],'#253b45',7);lantern(x+43,466,.8);}else{barrel(x,650,.9);if(i%3===0)crate(x+50,650,48);}}if(G.layout===2||G.layout===6||G.layout===10){poly([[0,0],[G.world,0],[G.world,120],[2100,160],[1900,90],[1720,220],[1490,110],[1250,175],[1080,80],[900,170],[650,105],[380,180],[170,95],[0,190]],'#0c1a2cef');for(let i=0;i<14;i++){let x=i*210;poly([[x,60],[x+40,250+(i%4)*20],[x+85,90]],'#122435');}}}
for(let r of G.ropes){let sway=Math.sin(G.t*1.5+r.x)*3;line([[r.x,r.y],[r.x+sway,r.bottom]],'#b2a27b',4);for(let y=r.y;y<r.bottom;y+=19)line([[r.x-3,y],[r.x+3,y+5]],'#40505a',2);line([[r.x-28,r.y],[r.x+28,r.y]],'#233b47',9);}for(let p of G.platforms)drawPlatform(p);
if(G.worldMode!=='hub'&&G.room<6){for(let p of G.platforms.filter(p=>!p.ground)){if(Math.floor(p.x)%3===0)barrel(p.x+p.w-35,p.y,.68);}}for(let d of G.doors)drawDoor(d);for(let n of G.npcs){drawRig({x:n.x,y:n.y,face:-1,walk:0,type:n.type==='rosa'?'rosa':n.type==='smith'||n.type==='merchant'?'merchant':'lighthouse',hp:1},false);label(n.name,n.x,n.y-137,13,'#f2d6a6');if(Math.abs(G.p.x-n.x)<120)glow(n.x,n.y-55,90,'#eabd7015');}}
function drawDoor(d){let open=G.worldMode==='hub'||G.cleared;ctx.save();ctx.translate(d.x,d.y);glow(0,-65,120,open?'#e3b96727':'#7596a90b');poly([[-42,0],[-42,-105],[-25,-126],[25,-126],[42,-105],[42,0]],'#132736','#9e8f6a',4);const grad=ctx.createLinearGradient(-30,-100,30,0);grad.addColorStop(0,open?'#d8b66a90':'#243c4a');grad.addColorStop(1,'#10273d');ctx.fillStyle=grad;ctx.fillRect(-32,-99,64,98);for(let i=-20;i<=20;i+=20)line([[i,-95],[i,0]],'#15314766',2);if(open){let a=.5+Math.sin(G.t*2)*.3;ctx.globalAlpha=a;line([[0,-84],[0,-20],[11,-33]],'#ffe2a5',4);ctx.globalAlpha=1;}else{line([[-29,-82],[30,-18]],'#36414b',6);line([[30,-82],[-29,-18]],'#36414b',6);}let symbol=({smile:'☼',gold:'◈',heal:'♡',weapon:'⚔',boss:'♛',depart:'⚓'})[d.type];ellipse(0,-150,23,23,'#0d2131');ctx.strokeStyle=open?'#d5b876':'#556572';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,-150,23,0,Math.PI*2);ctx.stroke();label(symbol,0,-149,25,open?'#f8d593':'#6e8796');label(d.label||rewardName(d.type),0,-185,12,open?'#ebd4aa':'#93a4b2');ctx.restore();}
const HERO=new Image();HERO.src=ASSETS.hero||'';const FLAIL=new Image();FLAIL.src=ASSETS.flail||'';const ENEMIES=new Image();ENEMIES.src=ASSETS.enemies||'';
function drawHeroSprite(p,ghost=false){let flail=G.run?.weapon==='flail'&&FLAIL.naturalWidth,image=flail?FLAIL:HERO;if(!image.complete||!image.naturalWidth)return false;let frame=4;let moving=Math.abs(p.vx||0)>55&&p.ground;if(moving)frame=Math.floor(p.walk*1.1)%4;if(!p.ground)frame=p.vy<0?5:6;if(p.attack>0)frame=7+p.combo;if(p.parry>0)frame=10;if(p.dash>0)frame=11;if(p.rope)frame=5;const boxes=ASSETS.frames?.[flail?'hero-flail-atlas':'hero-atlas'];if(!boxes)return false;let b=boxes[frame],pivot=[193,530,925,1258,185,548,900,1200,215,555,950,1270][frame],scale=flail?.338:.35;ctx.save();ctx.translate(p.x,p.y);ctx.scale(p.face||1,1);if(p.hurt>0&&!ghost)ctx.globalAlpha=.6+Math.sin(G.t*70)*.3;if(p.dash>0){ctx.translate(0,-32);ctx.rotate((.25-p.dash)*Math.PI*5);ctx.translate(0,32);}let bob=moving?Math.sin(p.walk*2)*1.5:Math.sin(G.t*2.8)*.7;ctx.drawImage(image,b[0],b[1],b[2]-b[0],b[3]-b[1],(b[0]-pivot)*scale,-(b[3]-b[1])*scale+bob,(b[2]-b[0])*scale,(b[3]-b[1])*scale);ctx.restore();return true;}

function drawRig(a,hero=false,ghost=false){let moving=Math.abs(a.vx||0)>25,walk=a.walk||0,face=a.face||1,type=a.type||'hero',boss=type==='boss',scale=boss?1.42:type==='elite'?1.16:1;let airborne=hero&&!a.ground;ctx.save();ctx.translate(a.x,a.y);ctx.scale(face*scale,scale);if(a.dead>0){ctx.translate(0,-30);ctx.rotate(-1.2*(1-a.dead/.65));ctx.globalAlpha=a.dead/.65;}if(a.hurt>0)ctx.globalAlpha=.75;let bob=moving?Math.sin(walk*2)*2.2:Math.sin(G.t*2.5+a.x)*1.5;ctx.translate(0,bob);if(hero&&a.dash>0){ctx.translate(0,-28);ctx.rotate((.25-a.dash)*Math.PI*5);ctx.translate(0,28);}let shirt=hero?'#e6e4ca':type==='rosa'?'#bb856c':type==='lighthouse'?'#719292':type==='merchant'?'#807097':boss?'#795574':type==='elite'?'#576f78':type==='rope'?'#698484':'#6a7d89',skin=hero?'#deb78d':boss?'#b78465':'#c69e78',pants=hero?'#25303e':'#283343';let legA=moving?Math.sin(walk)*23:7,legB=moving?Math.sin(walk+Math.PI)*23:-7;if(airborne){legA=-16;legB=21;}function limb(points,color,w){line(points,'#101d2c',w+4);line(points,color,w);}
limb([[-7,-42],[legB*.6,-24],[legB,-5]],'#202b39',12);limb([[8,-42],[legA*.6,-24],[legA,-5]],pants,13);line([[legB-6,-3],[legB+9,-3]],'#4a3d34',11);line([[legA-5,-3],[legA+12,-3]],'#6c5141',11);let armBack=moving?Math.sin(walk)*15:0;limb([[-10,-71],[-23-armBack,-49],[-13-armBack,-40]],shirt,12);ellipse(-13-armBack,-38,6,7,skin);
poly([[-15,-75],[8,-80],[20,-66],[14,-43],[-15,-41],[-20,-61]],shirt,'#152233',3);poly([[3,-77],[-2,-53],[9,-68]],'#f8e4bc');line([[0,-73],[0,-54]],'#59666c',2);for(let i=0;i<3;i++)line([[-4,-68+i*6],[4,-66+i*6]],'#a99c7e',1.5);poly([[-17,-46],[17,-47],[17,-36],[-16,-34]],hero?'#a34444':'#945b4c','#26303b',2);poly([[9,-39],[22+Math.sin(G.t*7)*5,-17],[11,-22],[7,-39]],hero?'#c65950':'#9e7060');poly([[9,-37],[32+Math.sin(G.t*8)*6,-30],[25,-22],[9,-34]],'#823b40');
ellipse(1,-88,17,21,skin);ellipse(-13,-86,6,7,skin);poly([[-16,-86],[-19,-101],[-7,-111],[6,-105],[19,-100],[18,-90],[8,-99],[-1,-91],[-8,-98],[-12,-85]],hero?'#6f4d31':'#473f35','#13202e',2);poly([[-16,-98],[-32,-89],[-25,-103],[-12,-105]],'#51412e');line([[8,-88],[14,-87]],'#23303a',2);line([[14,-85],[18,-80],[13,-80]],'#956f52',2);line([[7,-76],[14,-75]],'#604d41',1.5);if(!hero&&['sailor','boss','elite','rope'].includes(type)){poly([[-27,-101],[-14,-123],[2,-117],[22,-123],[33,-101],[1,-96]],boss?'#293041':'#354b56','#101d2c',3);line([[-21,-102],[23,-102]],'#be9967',3);label(boss?'♛':'×',3,-109,14,'#e4c69b');if(boss)poly([[-8,-73],[1,-56],[14,-74]],'#4b3941');}if(type==='lighthouse'){ellipse(7,-87,7,7,'#c0d4c340');line([[0,-88],[16,-88]],'#c8c1a3',1);poly([[-16,-103],[15,-103],[10,-119],[-10,-119]],'#566a72');}if(type==='merchant'){poly([[-20,-101],[18,-101],[13,-117],[-9,-121]],'#8e6e87');}if(type==='rosa'){poly([[-20,-96],[-18,-117],[9,-113],[20,-97],[6,-104]],'#704537');}
let ax=28,ay=-50,swordAngle=.3;if(hero&&a.parry>0){ax=25;ay=-72;swordAngle=-1.1;}else if(a.state==='windup'){ax=6;ay=-98;swordAngle=-2;}else if(a.state==='attack'||hero&&a.attack>0){ax=36;ay=-68;swordAngle=hero&&a.combo===1?-1.1:-.15;}else if(moving){ax=22-Math.sin(walk)*13;ay=-49;}limb([[12,-69],[24,-57],[ax,ay]],shirt,12);ellipse(ax,ay,6,7,skin);
if(!['rosa','lighthouse','merchant'].includes(type)){ctx.save();ctx.translate(ax,ay);ctx.rotate(swordAngle);if(hero&&G.run?.weapon==='flail'){line([[0,0],[23,-4],[39,1]],'#999b91',3);ellipse(54,1,15,9,'#e8bc5d');ellipse(64,-7,7,7,'#e7c36e');poly([[69,-9],[80,-5],[69,-3]],'#d96b4b');line([[43,9],[42,17],[48,17]],'#ca8748',3);}else{line([[-7,0],[11,0]],'#a68553',6);poly([[12,-4],[61,-5],[79,-15],[68,1],[12,5]],'#c0d8d8','#243b49',2);line([[17,-3],[61,-3],[74,-11]],'#e7f4e6',1.5);line([[11,-13],[11,13]],'#b69560',4);}ctx.restore();}ctx.restore();}
function drawEnemySprite(e){if(!ENEMIES.complete||!ENEMIES.naturalWidth||!ASSETS.frames)return false;const boss=e.type==='boss'||e.type==='elite';let frame=0;if(Math.abs(e.vx)>15)frame=Math.floor(e.walk*.8)%2;if(e.state==='windup')frame=2;if(e.state==='attack')frame=3;let index=frame+(boss?4:0),b=ASSETS.frames['enemies-atlas'][index],pivot=[230,655,1060,1455,225,625,1090,1475][index],scale=e.type==='boss'?.40:e.type==='elite'?.33:.32;ctx.save();ctx.translate(e.x,e.y);ctx.scale(e.face,1);if(e.dead>0){ctx.globalAlpha=e.dead/.65;ctx.rotate(-1.3*(1-e.dead/.65));}if(e.hurt>0)ctx.globalAlpha=.75;let bob=Math.abs(e.vx)>15?Math.sin(e.walk*2)*2:Math.sin(G.t*2.5+e.id)*1.3;if(e.state==='windup')ctx.translate(-Math.sin((1-e.timer/e.windup)*Math.PI)*5,0);ctx.drawImage(ENEMIES,b[0],b[1],b[2]-b[0],b[3]-b[1],(b[0]-pivot)*scale,-(b[3]-b[1])*scale+bob,(b[2]-b[0])*scale,(b[3]-b[1])*scale);if(e.type==='rope')line([[22,-65],[35,-64],[39,-52],[32,-45],[24,-50]],'#c5d4d3',4);ctx.restore();return true;}

function drawCrab(e){ctx.save();ctx.translate(e.x,e.y);ctx.scale(e.face,1);if(e.dead>0)ctx.globalAlpha=e.dead/.65;let t=e.walk;for(let side of [-1,1])for(let i=0;i<3;i++){let x=side*(14+i*3);line([[x,-12],[side*(30+i*2),-13+Math.sin(t+i)*4],[side*(36+i*2),-2]],'#142b39',6);line([[x,-12],[side*(30+i*2),-13+Math.sin(t+i)*4],[side*(36+i*2),-2]],'#b28663',3);}ellipse(0,-22,28,17,e.hurt>0?'#e0b28b':'#ae7357');poly([[-21,-31],[-9,-40],[17,-36],[27,-24],[7,-26]],'#d6996b');for(let x of [-10,10]){line([[x,-29],[x*1.2,-42]],'#a7815d',4);ellipse(x*1.2,-42,5,5,'#e4d8b0');ellipse(x*1.2+1,-42,2,3,'#0c1c29');}let raise=e.state==='windup'?20:0;line([[19,-21],[38,-27-raise]],'#bb8d62',7);poly([[34,-33-raise],[47,-42-raise],[46,-29-raise],[55,-37-raise],[53,-21-raise],[35,-20-raise]],'#d6a37b','#394044',2);ctx.restore();}
function drawEntity(e,hero=false){if(!hero&&e.hp<=0&&e.dead<=0)return;let gy=e.y;ellipse(e.x,gy+1,e.type==='boss'?52:27,7,'#030c1680');if(hero){if(e.invul>0&&Math.floor(G.t*18)%2===0)ctx.globalAlpha=.6;if(!drawHeroSprite(e))drawRig(e,true);ctx.globalAlpha=1;if(e.parry>0){ctx.save();ctx.translate(e.x+e.face*16,e.y-48);ctx.strokeStyle='#b6f7e6';ctx.shadowColor='#70e7df';ctx.shadowBlur=14;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,53,-1.35+(e.face===-1?Math.PI:0),1.35+(e.face===-1?Math.PI:0));ctx.stroke();ctx.restore();}}else if(e.type==='crab')drawCrab(e);else if(!drawEnemySprite(e))drawRig(e);
if(!hero&&e.hp>0){if(e.hp<e.maxHp&&e.type!=='boss'){roundRect(e.x-26,e.y-e.h-39,52,4,2,'#0a1628');roundRect(e.x-26,e.y-e.h-39,52*e.hp/e.maxHp,4,2,e.type==='elite'?'#e7bd75':'#deaaa0');}if(e.state==='windup'){let ready=e.timer<=.3+meta.upgrades.parry*.025;let color=ready?'#ffdc81':'#b48ad7';glow(e.x,e.y-e.h-30,ready?58:28,ready?'#ffbd6745':'#b07cdc20');label(ready?'✦':'!',e.x,e.y-e.h-37,ready?36:24,color);if(e.type==='boss'&&meta.bossKnown){label('받아치기!',e.x,e.y-e.h-78,15,'#aaf3e6');}}if(e.stun>0){for(let i=0;i<3;i++){let a=G.t*4+i*2.1;label('✧',e.x+Math.cos(a)*21,e.y-e.h-18+Math.sin(a)*5,14,'#dfd78d');}}if(e.tauntTime>0&&e.type!=='boss'){ctx.font=`11px ${FONT}`;let width=Math.min(240,ctx.measureText(e.taunt).width+24);roundRect(e.x-width/2,e.y-e.h-92,width,28,5,'#0c1c2be8','#d3b68066');label(e.taunt,e.x,e.y-e.h-78,11,'#e5cfab');}if(e.type==='boss'&&e.tauntTime>0){label(e.taunt,e.x,e.y-e.h-83,18,'#e7cfb7');}}}
function drawSlash(s){ctx.save();ctx.translate(s.x,s.y);ctx.globalAlpha=clamp(s.time/s.max,0,1);if(s.blast){let r=210*(1-s.time/s.max);glow(0,0,Math.max(10,r),'#ffa74490');ctx.strokeStyle='#fbd8a1';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.stroke();}else if(s.chicken){let t=1-s.time/s.max;ctx.rotate(t*Math.PI*4);ctx.strokeStyle='#f4ca72';ctx.lineWidth=4;ctx.setLineDash([9,12]);ctx.beginPath();ctx.arc(0,0,140*t+25,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);label('꽥!',70,0,30,'#ffe9af');}else{ctx.scale(s.face||1,1);let t=1-s.time/s.max;ctx.rotate(s.combo===1?-1.1:.15);ctx.lineWidth=s.parry?18:s.combo===2?15:9;ctx.strokeStyle=s.enemy?'#f1a78c':s.parry?'#b9fff1':s.flail?'#f9d580':'#d6f8e6';ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=16;ctx.beginPath();ctx.ellipse(-22,0,s.combo===2?133:105,63,0,-1.5+t*.5,1.3-t*.4);ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle='#ffffff';ctx.beginPath();ctx.ellipse(-19,0,s.combo===2?144:116,70,0,-1.35,1.15);ctx.stroke();}ctx.restore();}
function render(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,W,H);drawBackdrop();if(G.mode==='title'){drawAmbient();return;}ctx.save();let sx=G.shake?rand(-G.shake,G.shake):0,sy=G.shake?rand(-G.shake*.5,G.shake*.5):0;ctx.translate(-G.camera+sx,sy);drawEnvironment();for(let gh of G.ghosts){ctx.globalAlpha=gh.time/.22*.25;if(!drawHeroSprite({...gh,dash:.15},true))drawRig({...gh,dash:.15},true,true);}ctx.globalAlpha=1;for(let d of G.drops){glow(d.x,d.y,17,'#ffcc6633');ellipse(d.x,d.y,5,6,'#ebc276');ellipse(d.x-1,d.y-1,2,3,'#ffedb0');}for(let e of G.enemies)drawEntity(e);drawEntity(G.p,true);for(let p of G.projectiles){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(G.t*10);if(p.type==='bomb'){ellipse(0,0,13,16,'#5d5143');line([[-10,-3],[10,-3]],'#a78650',3);line([[0,-16],[4,-23]],'#cba765',2);glow(4,-23,15,'#ffd68977');ellipse(4,-23,3,3,'#ffe0a3');}else if(p.type==='wave'){ctx.rotate(-G.t*10);glow(0,0,35,'#ec946b44');line([[-14,15],[0,-30],[12,10]],'#f4bd89',5);}else{line([[-15,0],[10,0],[16,9],[9,16],[0,12]],'#bcc9c9',4);}ctx.restore();}for(let s of G.slashes)drawSlash(s);for(let p of G.particles){ctx.globalAlpha=clamp(p.life/.3,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size);}ctx.globalAlpha=1;for(let f of G.texts){ctx.globalAlpha=clamp(f.time/.3,0,1);ctx.strokeStyle='#0b1d2e';ctx.lineWidth=4;ctx.font=`800 ${f.size}px ${FONT}`;ctx.textAlign='center';ctx.strokeText(f.text,f.x,f.y);ctx.fillStyle=f.color;ctx.fillText(f.text,f.x,f.y);}ctx.globalAlpha=1;ctx.restore();
// Foreground framing travels faster than the camera, emphasizing movement.
ctx.save();ctx.translate(-G.camera*1.18,0);for(let i=0;i<8;i++){let x=i*580-50;line([[x,820],[x+8,706]],'#071320',24);line([[x+8,723],[x+165,760],[x+335,727]],'#0a1827',6);}ctx.restore();if(G.mode==='play'&&!G.cleared){let left=G.enemies.filter(e=>e.hp>0&&e.x<G.camera-20).length,right=G.enemies.filter(e=>e.hp>0&&e.x>G.camera+W+20).length;if(left)label('← 적 '+left,55,420,13,'#e9c18d');if(right)label('적 '+right+' →',W-55,420,13,'#e9c18d');}const vignette=ctx.createRadialGradient(W/2,H/2,250,W/2,H/2,850);vignette.addColorStop(0,'transparent');vignette.addColorStop(1,'#030c185e');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);drawAmbient();if(G.flash>0&&!meta.reduced){ctx.fillStyle=`rgba(205,235,235,${G.flash*.4})`;ctx.fillRect(0,0,W,H);}if(G.banner){let opacity=Math.min(1,G.banner.time,3-G.banner.time+.1);ctx.globalAlpha=Math.max(.05,opacity);let y=235;let grad=ctx.createLinearGradient(W/2-450,0,W/2+450,0);grad.addColorStop(0,'#07142500');grad.addColorStop(.3,'#071425cb');grad.addColorStop(.7,'#071425cb');grad.addColorStop(1,'#07142500');ctx.fillStyle=grad;ctx.fillRect(W/2-450,y-46,900,103);label(G.banner.sub,W/2,y-20,12,'#d7b779');label(G.banner.title,W/2,y+16,G.banner.title.length>20?23:30,'#f2e2c5');ctx.globalAlpha=1;}}
function drawAmbient(){for(let i=0;i<30;i++){let x=(i*151+Math.sin(G.t*.3+i)*55-G.t*(i%3+1)*4)%W;if(x<0)x+=W;let y=(i*89+Math.cos(G.t*.5+i)*19)%H;let a=.1+Math.sin(G.t+i)*.08;ctx.fillStyle=`rgba(236,217,164,${a})`;ctx.beginPath();ctx.arc(x,y,1.2+i%2*.5,0,Math.PI*2);ctx.fill();}}
function btn(text,action,cls='',disabled=false){return `<button class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`;}
function openModal(content,cls=''){if(['play','hub'].includes(G.mode))G.backMode=G.mode;G.mode='dialog';keys.clear();pressed.clear();$('#overlay').className='open';$('#overlay').style.background='';$('#overlay').style.backdropFilter='';$('#overlay').innerHTML=`<section class="modal ${cls}" role="dialog" aria-modal="true">${content}</section>`;$('#overlay button')?.focus();}
function closeOverlay(){keys.clear();pressed.clear();$('#overlay').className='';$('#overlay').innerHTML='';G.mode=G.backMode||'hub';}
function title(){G.mode='title';G.worldMode='title';$('#hud').hidden=true;$('#overlay').className='open';$('#overlay').style.background='transparent';$('#overlay').style.backdropFilter='none';$('#overlay').innerHTML=`<section class="modal title-modal"><span class="eyebrow">A MOONLIT ACTION ROGUELITE</span><div class="title-small">The Secret of</div><div class="title-logo">DentPhoto<span>Village</span></div><p>달빛 아래, 칼끝보다 날카로운 한마디.<br>뛰어들고, 흘려내고, 받아쳐라.<br>사진사가 훔친 마을의 미소를 되찾는 밤이 시작된다.</p><div class="actions">${btn(meta.runs?'술집으로 돌아가기 →':'모험 시작 →','start','primary')}${btn('조작 방법','help')}${btn(meta.sound?'♫ 소리 켜짐':'♫ 소리 꺼짐','sound')}</div></section><div class="title-foot">CHAPTER 01 · THE MOONLIT HARBOR<br>키보드 / 게임패드 · ACTION EDITION<br>2026 · 아울러</div>`;$('#overlay button')?.focus();}
function endingPreview(){openModal(`${btn('×','resume','close-x')}<span class="eyebrow">CHAPTER 01 COMPLETE · THE LAST WORD</span><h1>“좋아. 네 말이 더 날카롭군.”</h1><p>브락은 모자를 벗고 한참을 웃었습니다.<br>“사진사에게 가려면 절벽 지붕길로 가. 그리고 이건… 내가 못 전한 초대장이야.”<br>닫혀 있던 항구의 등불이 하나둘 켜지고, 밤바다 위로 주민들의 미소가 번집니다.</p><div class="end-summary"><span>부두 지역 완료</span><span>처치 18</span><span>받아치기 7회</span><span>금니 +3</span></div><p class="hint">이 장면 뒤에는 절벽 마을과 저택의 사진사가 기다리고 있습니다.<br>실제 플레이에서는 8개 방을 돌파하고 선장 브락을 쓰러뜨리면 이 화면에 도착합니다.</p><div class="actions">${btn('처음 화면으로','title-return','primary')}${btn('실제 항해 시작','start')}</div>`);G.backMode='title';}
function help(){let wasTitle=G.mode==='title';openModal(`${btn('×','resume','close-x')}<span class="eyebrow">HOW TO PLAY</span><h1>한 박자 기다렸다가,<br>기막히게 받아치세요.</h1><div class="control-grid"><div><strong>움직이기 · ← → / A D</strong><p>Space로 2단 점프. 밧줄 곁에서 ↑를 누르면 잡고 오릅니다. 게임패드: 스틱 / A.</p></div><div><strong>3타 공격 · J</strong><p>연속으로 눌러 3타 콤보. 마지막 일격은 적을 밀어냅니다. 게임패드: X.</p></div><div><strong>구르기 · K</strong><p>짧은 무적 시간으로 적을 통과합니다. 위험하면 뒤로 물러나세요. 게임패드: B.</p></div><div><strong>받아치기 · L</strong><p>적 머리 위 금빛 ✦가 빛날 때! 약 0.3초 안의 공격을 반격합니다. 게임패드: RB.</p></div><div><strong>소품 · U / I</strong><p>고무 닭은 주변 공격과 기절, 럼 폭탄은 원거리 폭발. 게임패드: LT / RT.</p></div><div><strong>필살 대사 · O</strong><p>웃음 100%에서 광역 공격. 주민·문 곁에서 E로 상호작용. 게임패드: Y / LB.</p></div></div><p class="hint">Escape / Start: 일시정지 · Tab / Enter: 메뉴 선택<br>부두 8개 방 → 중간 강적 → 떠돌이 상인 → 선장 브락. 전투가 끝나면 문 위의 보상을 고르세요.<br>이 버전은 1지역 완성형 프로토타입입니다. 금니·필름·단서·강화는 자동 저장하며, 진행 중인 방과 빌드는 게임을 닫으면 초기화됩니다.</p><div class="actions">${btn('알겠어, 해 보자','resume','primary')}</div>`);if(wasTitle)G.backMode='title';}
function pause(){G.backMode=G.mode;openModal(`${btn('×','resume','close-x')}<span class="eyebrow">A MOMENT TO CATCH YOUR BREATH</span><h1>잠깐, 숨 돌리기.</h1><p>파도도 당신을 기다립니다.</p><div class="actions">${btn('계속하기 →','resume','primary')}${btn('조작 방법','help')}${btn('단서와 미소','journal')}${btn('전체 화면','fullscreen')}</div><div class="actions">${btn(meta.sound?'♫ 소리 켜짐':'♫ 소리 꺼짐','sound')}${btn(meta.reduced?'화면 흔들림 꺼짐':'화면 흔들림 켜짐','motion')}${btn('영구 기록 내보내기','export')}${btn('영구 기록 불러오기','import')}</div><p class="hint">영구 기록은 자동 저장됩니다. 현재 항해는 브라우저를 닫으면 종료됩니다.</p>${G.run?`<div class="actions">${btn('이번 항해를 마치고 술집으로','abandon')}</div>`:''}`);G.mode='paused';}
function resume(){if(G.offers?.length)return;let mode=G.backMode;closeOverlay();if(mode==='title'){title();return;}G.mode=mode||'hub';audioStart();}
function npcTalk(type){if(type==='rosa'){if(!meta.clues.includes('rumor')){meta.clues.push('rumor');save();}openModal(`${btn('×','resume','close-x')}<span class="eyebrow">밤의 갈매기 · 로사</span><h1>${meta.runs?'사진은 잘 나왔더라.':'칼이 서툴면, 말로 이기면 되지.'}</h1><p>${meta.runs?'“다음번엔 눈 좀 뜨고 찍혀. 현상액 값이 얼만데.”<br>로사는 따뜻한 수건을 건넸습니다. “넘어진 건 잊어. 네가 돌려준 미소는 아직 여기 있으니까.”':'“요즘 마을 사람들은 웃어도 이가 안 보인단다. 절벽 위 저택에서 플래시가 번쩍인 뒤부터야. 부두의 브락 선장이 뭔가를 알고 있을 거야.”'}</p><p class="hint">단서 획득 · 밤마다 사라지는 미소<br>받아치기와 3타 콤보로 관중 웃음을 모으세요. 맞으면 웃음이 조금 줄어듭니다.</p><div class="actions">${btn('좋아, 할 말은 준비됐어','resume','primary')}${btn('조작 방법','help')}</div>`);}else if(type==='lighthouse')upgradeMenu();else if(type==='smith')smithMenu();else merchantMenu();}
const UPGRADES=[['health','든든한 체면','시작 최대 체면 +12','♡'],['parry','한 박자 긴 여유','받아치기 판정 +0.025초','✦'],['flask','따뜻한 럼차','회복 보상 +5, 입장마다 체면 +2','♨'],['smile','소문난 말재주','출항 때 미소 선택. 추가 강화마다 선택지 +1 (최대 5장)','☼']];
function upgradeMenu(){openModal(`${btn('×','resume','close-x')}<span class="eyebrow">등대지기 노아 · 영구 강화</span><h1>불빛은, 꺼져도 다시 켜면 돼.</h1><p>금니 <strong style="color:var(--gold)">${meta.teeth}</strong>개 · “한밤중에도 배울 수 있는 게 있지.”</p><div class="stat-grid">${UPGRADES.map(([id,name,desc,icon])=>{let lv=meta.upgrades[id],cost=2+lv*2;return btn(`<strong>${icon} ${name} <small>${lv} / 5</small></strong><small>${desc}</small><span>${lv>=5?'최대 강화':cost+' 금니'}</span>`,'upgrade:'+id,'upgrade',lv>=5||meta.teeth<cost);}).join('')}</div><p class="hint">금니는 강적과 보스에게서 얻습니다. 강화는 다음 출항부터 적용됩니다.</p>`);}
function smithMenu(){openModal(`${btn('×','resume','close-x')}<span class="eyebrow">생선 장수 마리 · 무기 보관함</span><h1>칼보다 닭이 강할 때도 있지.</h1><p>보유 필름 ${meta.film} · 무기를 골라 다음 항해에 가져가세요.</p><div class="cards" style="grid-template-columns:1fr 1fr">${btn('<span class="icon">⚔</span><strong>녹슨 커틀러스</strong><p>빠른 3타 콤보. 받아치기 반격 피해 +8.</p><em>기본 무기 · 출항 무기로 선택</em>','equip:sword','boon-card')}${btn(`<span class="icon">♧</span><strong>고무 닭 플레일</strong><p>넓은 사거리, 묵직한 일격. 타격할 때 웃음이 더 빨리 찹니다.</p><em>${meta.flail?'해금 완료 · 출항 무기로 선택':'영구 해금 · 필름 5개'}</em>`,meta.flail?'equip:flail':'unlock','boon-card',!meta.flail&&meta.film<5)}</div><p class="hint">현재 선택: ${G.equipped==='flail'?'고무 닭 플레일':'녹슨 커틀러스'}. 방의 무기 보상에서는 아직 해금하지 않은 무기도 이번 항해에 사용할 수 있습니다.</p>`);}
function merchantMenu(){openModal(`${btn('×','resume','close-x')}<span class="eyebrow">떠돌이 상인 · 선장전 준비</span><h1>살아 돌아오면, 단골이지.</h1><p>보유 금화 ${G.run.gold} · 현재 체면 ${Math.ceil(G.run.hp)} / ${G.run.maxHp}</p><div class="stat-grid">${btn('<strong>♨ 따뜻한 럼차</strong><small>체면 40 회복</small><span>25 금화</span>','buyheal','upgrade',G.run.gold<25||G.run.hp>=G.run.maxHp)}${btn('<strong>☼ 되찾지 못한 미소</strong><small>미소 하나를 골라 힘을 얻습니다.</small><span>50 금화</span>','buysmile','upgrade',G.run.gold<50||G.run.boons.length>=9)}${btn('<strong>♧ 고무 닭 플레일</strong><small>이번 항해의 주무기를 교체합니다.</small><span>35 금화</span>','buyweapon','upgrade',G.run.gold<35||G.run.weapon==='flail')}${btn('<strong>♛ 선장을 만나러 간다</strong><small>거래를 마치고 출구로 걸어가세요.</small><span>행운은 무료</span>','resume','upgrade')}</div>`);}
function chooseBoon(context='next'){if(context===true)context='start';G.boonContext=context;let pool=BOONS.filter(b=>!G.run.boons.includes(b.id));if(!pool.length){G.run.hp=Math.min(G.run.maxHp,G.run.hp+25);if(context==='next')loadRoom(G.room+1);return;}G.offers=shuffle(pool).slice(0,context==='start'?Math.min(5,2+meta.upgrades.smile):3);openModal(`<span class="eyebrow">A SMILE SET FREE</span><h1>사진 속에서, 미소가 돌아왔다.</h1><p>주민 한 사람의 마음이 이번 항해에 힘을 보탭니다.</p><div class="cards" ${G.offers.length>3?'style="grid-template-columns:repeat('+G.offers.length+',1fr)"':''}>${G.offers.map(b=>btn(`<span class="icon">${b.icon}</span><small>${b.who}</small><strong>${b.name}</strong><p>${b.desc}</p><em>${b.quote}</em>`,'boon:'+b.id,'boon-card')).join('')}</div><p class="hint">등대지기의 ‘말문을 닫는 빛’ + 생선 장수의 ‘비린내 나는 칼끝’ = 기절한 적에게 독 피해 3배.</p>`);}
function takeBoon(id){if(!G.offers?.some(b=>b.id===id)||!G.run||G.run.boons.includes(id))return;G.run.boons.push(id);let b=BOONS.find(b=>b.id===id);if(!meta.residents.includes(b.who)){meta.residents.push(b.who);toast(b.who+'의 미소가 술집으로 돌아왔습니다.');}if(id==='heart'){G.run.maxHp+=20;G.run.hp+=20;}if(id==='radiance')addLaugh(25);save();let context=G.boonContext;G.offers=null;closeOverlay();if(context==='next')loadRoom(G.room+1);else if(context==='shop')merchantMenu();else{G.mode='play';updateHUD();}}
function weaponReward(){openModal(`<span class="eyebrow">A MOST UNUSUAL ARMORY</span><h1>뭘로 말문을 막을까요?</h1><div class="cards" style="grid-template-columns:1fr 1fr">${btn('<span class="icon">⚔</span><strong>녹슨 커틀러스</strong><p>빠른 콤보와 강한 받아치기 반격.</p>','weapon:sword','boon-card')}${btn('<span class="icon">♧</span><strong>고무 닭 플레일</strong><p>느리지만 넓은 공격. 맞힐 때마다 더 큰 웃음.</p>','weapon:flail','boon-card')}</div>`);}
function journal(){let wasTitle=G.mode==='title';openModal(`${btn('×','resume','close-x')}<span class="eyebrow">THE SMILE JOURNAL</span><h1>웃음의 행방</h1>${[['rumor','밤마다 사라지는 미소','로사가 들려준 소문. 저택의 플래시가 터진 뒤부터 주민들이 웃지 못한다.'],['tooth','금니에 새겨진 D.P.','부두에서 발견한 금니에는 사진사의 이니셜이 새겨져 있다. 오래된 선장의 유품일까?'],['captain','브락이 숨긴 초대장','브락이 지키던 초대장에는 “당신의 미소를 영원히”라는 문구가 적혀 있다.']].map(([id,title,text])=>`<div class="journal-row"><strong>${meta.clues.includes(id)?'✧ '+title:'○ 아직 찾지 못한 단서'}</strong><p>${meta.clues.includes(id)?text:'주민과 대화하고 부두를 돌파하면 발견할 수 있습니다.'}</p></div>`).join('')}<div class="journal-row"><strong>브락의 말버릇</strong><p>${meta.bossKnown?'“진짜 선장”이라는 말 이후 공격이 빨라진다. 다음 대결에서는 예고 표시가 더 눈에 띈다.':'브락에게 패배하면 말버릇을 기록합니다.'}</p></div>${G.run?`<h2 style="margin-top:22px">이번 밤의 미소</h2><p>${G.run.boons.map(id=>BOONS.find(b=>b.id===id).name).join(' · ')||'아직 돌아온 미소가 없습니다.'}</p>`:''}`);if(wasTitle)G.backMode='title';}
function die(){if(G.mode!=='play')return;let photo='';try{photo=canvas.toDataURL('image/jpeg',.65);}catch(e){}if(G.room===7){meta.bossKnown=true;}save();G.flash=1;G.backMode='hub';let r=G.run;openModal(`<span class="eyebrow">DEVELOPED, NOT DEFEATED</span><h1>이번 사진은…<br>조금 흔들렸네요.</h1>${photo?`<div class="death-photo"><img src="${photo}" alt="사진에 갇힌 마지막 순간"><span>현상 완료 · 눈은 뜨고 찍자.</span></div>`:''}<p>눈부신 플래시. 당신은 납작한 사진이 되었습니다.<br>로사는 사진을 현상액에 담그더니 말했습니다.<br>“또 왔니? 다음엔 웃으면서 찍혀.”</p><div class="end-summary"><span>금니 +${r.teethGained}</span><span>필름 +${r.filmGained}</span><span>받아치기 ${r.parries}회</span></div><p class="hint">금니·필름·단서·주민의 귀환은 남았습니다. 현재 미소와 금화는 사라집니다.${G.room===7?'<br>브락의 말버릇을 기록했습니다. 다음 대결에 예고가 표시됩니다.':''}</p><div class="actions">${btn('따뜻한 술집으로 돌아가기 →','hub','primary')}</div>`);G.mode='dead';}
function victory(){if(G.mode!=='play')return;meta.wins++;if(!meta.clues.includes('captain'))meta.clues.push('captain');meta.teeth+=3;G.run.teethGained+=3;save();let r=G.run;openModal(`<span class="eyebrow">CHAPTER 01 COMPLETE</span><h1>“좋아. 네 말이 더 날카롭군.”</h1><p>브락은 모자를 벗고 한참을 웃었습니다.<br>“사진사에게 가려면 절벽 지붕길로 가. 그리고 이건… 내가 못 전한 초대장이야.”<br>닫혀 있던 항구의 등불이 하나둘 켜졌습니다.</p><div class="end-summary"><span>${Math.floor(r.time/60)}분 ${Math.floor(r.time%60)}초</span><span>처치 ${r.kills}</span><span>받아치기 ${r.parries}</span><span>금니 +${r.teethGained}</span></div><p class="hint">부두 지역을 완료했습니다. 이 버전의 플레이 가능한 범위는 여기까지입니다.<br>절벽 마을과 사진사의 저택은 후속 지역입니다. 지금은 무기와 미소를 바꾸어 다시 항해할 수 있습니다.</p><div class="actions">${btn('미소가 돌아온 술집으로 →','hub','primary')}</div>`);G.mode='victory';}
function exportMeta(){let url=URL.createObjectURL(new Blob([JSON.stringify(meta,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='DentPhoto-Action-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function action(a){let [cmd,id]=a.split(':');if(cmd==='start'){audioStart();hub();return;}if(cmd==='hub'){hub();return;}if(cmd==='depart'&&G.mode==='hub'){newRun();return;}if(cmd==='resume'){resume();return;}if(cmd==='help'){help();return;}if(cmd==='pause'){if(['play','hub'].includes(G.mode))pause();return;}if(cmd==='journal'){journal();return;}if(cmd==='sound'){meta.sound=!meta.sound;save();audioStart();if(G.mode==='title')title();else{let old=G.backMode;G.mode=old;pause();}return;}if(cmd==='motion'){meta.reduced=!meta.reduced;save();let old=G.backMode;G.mode=old;pause();return;}if(cmd==='fullscreen'){document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.().catch(()=>toast('전체 화면이 지원되지 않습니다.'));return;}if(cmd==='export'){exportMeta();return;}if(cmd==='import'){$('#import-file').click();return;}if(cmd==='abandon'){openModal('<h1>오늘 밤은 여기까지?</h1><p>금니와 필름, 단서는 남지만 이번 항해의 금화와 미소는 사라집니다.</p><div class="actions">'+btn('술집으로 돌아가기','hub','primary')+btn('계속 항해하기','resume')+'</div>');return;}if(cmd==='upgrade'&&UPGRADES.some(u=>u[0]===id)){let cost=2+meta.upgrades[id]*2;if(meta.teeth>=cost&&meta.upgrades[id]<5){meta.teeth-=cost;meta.upgrades[id]++;save();sfx('coin');upgradeMenu();}return;}if(cmd==='unlock'&&!meta.flail&&meta.film>=5){meta.film-=5;meta.flail=true;G.equipped='flail';save();smithMenu();return;}if(cmd==='equip'&&['sword','flail'].includes(id)&&(id==='sword'||meta.flail)){G.equipped=id;smithMenu();return;}if(cmd==='boon'){takeBoon(id);return;}if(!G.run)return;if(cmd==='weapon'&&['sword','flail'].includes(id)){G.run.weapon=id;closeOverlay();loadRoom(G.room+1);return;}if(cmd==='buyheal'&&G.run.gold>=25&&G.run.hp<G.run.maxHp){G.run.gold-=25;G.run.hp=Math.min(G.run.maxHp,G.run.hp+40);merchantMenu();return;}if(cmd==='buysmile'&&G.run.gold>=50&&G.run.boons.length<9){G.run.gold-=50;chooseBoon('shop');return;}if(cmd==='buyweapon'&&G.run.gold>=35){G.run.gold-=35;G.run.weapon='flail';merchantMenu();return;}}
document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(b&&!b.disabled){audioStart();action(b.dataset.action);}});
document.addEventListener('keydown',e=>{if(!$('#overlay').classList.contains('open'))return;if(e.key==='Tab'){let items=[...$('#overlay').querySelectorAll('button:not(:disabled)')];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}});
$('#import-file').addEventListener('change',async e=>{let f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>100000)throw Error();let d=JSON.parse(await f.text());if(!validMeta(d))throw Error();openModal(`<h1>이 영구 기록을 불러올까요?</h1><p>${d.runs}번 출항 · ${d.wins}번 부두 완료 · 금니 ${d.teeth} · 필름 ${d.film}<br>현재 항해는 끝나고 저장한 영구 기록으로 교체됩니다.</p><div class="actions"><button id="confirm-import" class="primary">기록 교체하기</button>${btn('취소','resume')}</div>`);$('#confirm-import').addEventListener('click',()=>{meta=d;save();hub();});}catch(e){toast('액션 버전의 올바른 저장 파일이 아닙니다.');}});
let last=0,acc=0;function frame(time){let dt=Math.min(.05,(time-last)/1000||1/60);last=time;acc+=dt;let steps=0;while(acc>=1/60&&steps<4){update(1/60);acc-=1/60;steps++;}render();requestAnimationFrame(frame);}
title();requestAnimationFrame(frame);
const actionOriginal=action; action=function(a){if(a==='ending-preview'){endingPreview();return;}if(a==='title-return'){title();return;}return actionOriginal(a);};
