const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let seed=42;const math=Object.create(Math);math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const storage=new Map(),els=new Map();let proxy=new Proxy({measureText:s=>({width:s.length*10}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
const make=()=>({innerHTML:'',hidden:false,style:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},querySelector(){return make()},querySelectorAll(){return[]},addEventListener(){},focus(){},click(){},getContext:()=>proxy});
let context={console,Math:math,structuredClone,JSON,Blob,URL,setTimeout:()=>0,Image:class{complete=false;naturalWidth=0},requestAnimationFrame(){},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},window:{addEventListener(){}},navigator:{getGamepads:()=>[]},document:{querySelector:s=>{if(!els.has(s))els.set(s,make());return els.get(s)},addEventListener(){},activeElement:make(),documentElement:{},createElement:make()}};
vm.createContext(context);vm.runInContext('const ASSETS={harbor:"",hero:""};'+fs.readFileSync(require('node:path').join(__dirname,'../src/game.js'),'utf8'),context);const run=s=>vm.runInContext(s,context);let count=0;function test(name,f){f();count++;console.log('PASS',name)}function setup(){run('meta=structuredClone(DEFAULT);meta.sound=false;newRun();if(G.mode==="dialog")resume();G.enemies=[];G.p.x=150;G.p.y=650;G.p.ground=true;G.p.vy=0;');}function step(n=1){for(let i=0;i<n;i++)run('update(1/60)')}
test('hub, twelve room templates, eight-stage run and first combat render',()=>{run('hub();render()');assert.equal(run('G.mode'),'hub');run('newRun();render()');assert.equal(run('LAYOUTS.length'),12);assert.equal(run('G.run.rooms.length'),8);assert.equal(run('new Set(G.run.rooms).size'),8);assert.equal(run('G.enemies.length'),3);});
test('movement, grounded jump, double jump, no third jump',()=>{setup();run(`keys.add('ArrowRight')`);step(30);assert.ok(run('G.p.x')>250);run(`keys.clear();pressed.add('jump')`);step();assert.ok(run('G.p.vy')<0);run(`pressed.add('jump')`);step();assert.equal(run('G.p.jumps'),2);let vy=run('G.p.vy');run(`pressed.add('jump')`);step();assert.equal(run('G.p.jumps'),2);assert.ok(run('G.p.vy')>vy);step(120);assert.equal(run('G.p.y'),650);});
test('dodge blocks incoming damage and has cooldown',()=>{setup();run(`pressed.add('dash')`);step();let hp=run('G.run.hp');run('hurtPlayer(20,{x:200})');assert.equal(run('G.run.hp'),hp);assert.ok(run('G.p.dashCD')>.6);});
test('well-timed parry reflects attack, builds laughter and respects expiry',()=>{setup();run(`let foe=spawnEnemy('sailor',210,650);G.p.parry=.3;hurtPlayer(13,foe)`);assert.equal(run('G.run.hp'),100);assert.equal(run('G.run.parries'),1);assert.equal(run('G.run.laugh'),24);assert.equal(run('foe.maxHp-foe.hp'),38);run('G.p.parry=0;G.p.invul=0;hurtPlayer(13,foe)');assert.equal(run('G.run.hp'),87);});
test('three attacks have increasing damage and cooldown prevents spam',()=>{setup();run(`let dummy=spawnEnemy('boss',220,650);dummy.hp=dummy.maxHp=1000;doAttack()`);assert.equal(run('dummy.hp'),983);run('doAttack()');assert.equal(run('dummy.hp'),983);run('G.p.attackCD=0;doAttack();G.p.attackCD=0;doAttack()');assert.equal(run('dummy.hp'),933);});
test('skills apply cooldown; bombs expire and ultimate spends laughter',()=>{setup();run(`spawnEnemy('boss',220,650);useSkill('U')`);let hp=run('G.enemies[0].hp');run(`useSkill('U')`);assert.equal(run('G.enemies[0].hp'),hp);run(`useSkill('I');updateProjectiles(1.3)`);assert.equal(run('G.projectiles.length'),0);run('G.run.laugh=100;ultimate()');assert.equal(run('G.run.laugh'),0);assert.ok(run('G.enemies[0].hp')<hp);});
test('locked exits, clear state, reward choice and next-room transition',()=>{setup();run(`loadRoom(0);G.p.x=G.doors[0].x;G.p.y=650;interact()`);assert.equal(run('G.mode'),'play');assert.equal(run('G.room'),0);run('G.enemies.forEach(e=>killEnemy(e));G.hitstop=0');step();assert.equal(run('G.cleared'),true);run('interact()');assert.equal(run('G.mode'),'dialog');run('takeBoon(G.offers[0].id)');assert.equal(run('G.room'),1);assert.equal(run('G.run.boons.length'),1);assert.equal(run('G.mode'),'play');});
test('permanent upgrades, unlock and starting weapon survive a new run',()=>{setup();run(`meta.teeth=10;action('upgrade:health');meta.film=7;action('unlock');newRun()`);assert.equal(run('G.run.maxHp'),112);assert.equal(run('G.run.weapon'),'flail');assert.equal(run('meta.teeth'),8);assert.equal(run('meta.film'),2);assert.equal(run('validMeta(JSON.parse(localStorage.getItem(KEY)))'),true);assert.equal(run('validMeta({version:1})'),false);});
test('merchant charges once per successful purchase and correct room retained',()=>{setup();run(`loadRoom(6);G.run.gold=60;G.run.hp=30;action('buyheal')`);assert.equal(run('G.run.gold'),35);assert.equal(run('G.run.hp'),70);run(`action('buysmile')`);assert.equal(run('G.run.gold'),35);run(`G.run.gold=80;action('buysmile');takeBoon(G.offers[0].id)`);assert.equal(run('G.run.gold'),30);assert.equal(run('G.room'),6);});
test('death preserves meta, learns boss tell and returns to hub',()=>{setup();run(`loadRoom(7);meta.teeth=3;G.run.hp=1;hurtPlayer(30,G.boss)`);assert.equal(run('G.mode'),'dead');assert.equal(run('meta.bossKnown'),true);run('hub()');assert.equal(run('G.run'),null);assert.equal(run('meta.teeth'),3);});
test('boss victory and journal clue complete chapter without repeated rewards',()=>{setup();run(`loadRoom(7);killEnemy(G.boss)`);step(200);assert.equal(run('G.mode'),'victory');assert.equal(run('meta.wins'),1);assert.equal(run('meta.clues.includes("captain")'),true);step(100);assert.equal(run('meta.wins'),1);});
test('all room layouts and every UI state render without exceptions',()=>{setup();for(let i=0;i<12;i++)run(`G.layout=${i};render()`);for(let code of ['help()','resume()','journal()','resume()','pause()','resume()','upgradeMenu()','resume()','smithMenu()','resume()','loadRoom(6)','merchantMenu()','resume()','loadRoom(7)'])run(code+';render()');});
test('title starts act 2 directly with the new villagers',()=>{run('meta=structuredClone(DEFAULT);meta.sound=false;title();action("act2");if(G.mode==="dialog")resume();render()');assert.equal(run('G.run.act'),2);assert.equal(run('G.mode'),'play');assert.equal(run('ROOF_LAYOUTS.length'),12);assert.equal(run('G.enemies.length'),3);assert.ok(run('G.enemies.every(e=>e.skin)'));assert.ok(run('G.ropes.length')>0);run('hub()');assert.ok(run('G.doors.some(d=>d.type==="depart2")'));run('G.p.x=G.doors.find(d=>d.type==="depart2").x;interact()');if(run('G.mode')==='dialog')run('resume()');assert.equal(run('G.run.act'),2);});
test('act 2 rooms, elite, merchant and clock tower boss render; boss rings midnight at half health',()=>{run('meta=structuredClone(DEFAULT);meta.sound=false;newRun(2);if(G.mode==="dialog")resume();');for(let i=0;i<12;i++)run(`G.layout=${i};render()`);run('loadRoom(3);render()');assert.equal(run('G.enemies.find(e=>e.type==="elite").skin'),'illusionist');run('loadRoom(6);render();loadRoom(7);render()');assert.equal(run('G.boss.skin'),'mechanic');run('G.boss.hp=G.boss.maxHp*.4;updateEnemy(G.boss,1/60);render()');assert.equal(run('G.boss.phase'),2);run('G.boss.state="windup";G.boss.timer=0;G.boss.pattern=2;updateEnemy(G.boss,1/60);render()');assert.ok(run('G.projectiles.filter(p=>p.type==="gear").length')===2);});
test('photographer flash and postman letters are projectiles that a parry sends back',()=>{run('meta=structuredClone(DEFAULT);meta.sound=false;newRun(2);if(G.mode==="dialog")resume();G.enemies=[];G.projectiles=[];G.p.x=150;G.p.y=650;');run('let cam=spawnEnemy("flash",450,650,"photographer");cam.state="windup";cam.timer=0;updateEnemy(cam,1/60);let post=spawnEnemy("rope",600,650,"postman");post.state="windup";post.timer=0;updateEnemy(post,1/60);render()');assert.equal(run('G.projectiles.map(p=>p.type).join()'),'flash,letter');let hp=run('cam.hp');run('G.p.parry=.3;hurtPlayer(12,cam)');assert.ok(run('cam.hp')<hp);assert.equal(run('G.run.parries'),1);});
test('clearing act 1 continues into act 2; act 2 victory and defeat keep their own records',()=>{run('meta=structuredClone(DEFAULT);meta.sound=false;newRun();if(G.mode==="dialog")resume();G.run.boons.push("heart");loadRoom(7);killEnemy(G.boss)');step(200);assert.equal(run('G.mode'),'victory');run('action("act2-continue")');assert.equal(run('G.run.act'),2);assert.equal(run('G.room'),0);assert.ok(run('G.run.boons.includes("heart")'));run('loadRoom(7);killEnemy(G.boss)');step(200);assert.equal(run('G.mode'),'victory');assert.equal(run('meta.act2Wins'),1);assert.ok(run('meta.clues.includes("clocktower")'));run('journal();resume();newRun(2);if(G.mode==="dialog")resume();loadRoom(7);G.run.hp=1;hurtPlayer(40,G.boss)');assert.equal(run('G.mode'),'dead');assert.equal(run('meta.clockKnown'),true);assert.equal(run('meta.bossKnown'),false);});
test('saves from before act 2 still load',()=>{assert.equal(run('{let old=structuredClone(DEFAULT);delete old.act2Wins;delete old.clockKnown;validMeta(old)}'),true);assert.equal(run('validMeta({...structuredClone(DEFAULT),act2Wins:-1})'),false);});
test('hero motion timers: take-off on the first jump, landing pose after touching down, climbing advances',()=>{setup();run(`pressed.add('jump')`);step();assert.ok(run('G.p.takeoff')>0);let landed=false;for(let i=0;i<120;i++){step();if(run('G.p.land')>0)landed=true;}assert.ok(landed);run('G.ropes=[{x:G.p.x,y:300,bottom:600}];G.p.rope=G.ropes[0];G.p.y=560;keys.add("ArrowUp")');step(20);assert.ok(run('G.p.climb')>1);run('keys.clear()');});
test('taunt bubbles hold still while the game is frozen by a hit-stop, and stacked bubbles do not jump',()=>{run('meta=structuredClone(DEFAULT);meta.sound=false;newRun(2);if(G.mode==="dialog")resume();G.enemies=[];let a=spawnEnemy("sailor",600,650,"sailor"),b=spawnEnemy("flash",640,650,"photographer");for(let e of [a,b]){e.taunt="이 매듭은 못 풀걸!";e.tauntTime=9;}G.hitstop=.1;render()');let first=run('G.enemies.map(e=>e.tauntY).join()');for(let i=0;i<6;i++)run('render()');assert.equal(run('G.enemies.map(e=>e.tauntY).join()'),first);for(let i=0;i<60;i++)run('render()');let [a,b]=run('G.enemies.map(e=>e.tauntY)');assert.ok(Math.abs(a-b)>=45);});
test('act 2 room clears open a villager conversation: the villager speaks, the hero picks one of two answers, the villager answers back',()=>{run('meta=structuredClone(DEFAULT);meta.sound=false;newRun(2);if(G.mode==="dialog")resume();G.enemies.forEach(e=>killEnemy(e));G.hitstop=0');step(120);assert.equal(run('G.mode'),'dialog');assert.equal(run('G.talk.who'),'kettle');assert.equal(run('G.talk.step'),0);run('resume()');assert.equal(run('G.mode'),'dialog');run('G.run.hp=50;action("talk:0")');assert.equal(run('G.talk.step'),1);assert.equal(run('G.run.hp'),62);assert.ok(run('meta.talks.includes("kettle")'));run('action("talk-end")');assert.equal(run('G.mode'),'play');assert.equal(run('G.talk'),null);assert.ok(run('G.cleared'));for(let room=1;room<6;room++){run(`loadRoom(${room});G.enemies.forEach(e=>killEnemy(e));G.hitstop=0`);step(120);assert.equal(run('G.talk.who'),run(`TALK_ORDER[${room}]`));let laugh=run('G.run.laugh');run('action("talk:1")');if(laugh<100)assert.ok(run('G.run.laugh')>laugh);run('action("talk-end")');}assert.equal(run('meta.talks.join()'),'kettle,postman,sailor,illusionist,photographer,mechanic');run('journal();resume()');run('loadRoom(6)');assert.equal(run('G.talk'),null);setup();run('loadRoom(0);G.enemies.forEach(e=>killEnemy(e));G.hitstop=0');step(120);assert.ok(!run('G.talk'));assert.notEqual(run('G.mode'),'dialog');assert.equal(run('validMeta({...structuredClone(DEFAULT),talks:[1]})'),false);});
console.log(`${count} tests passed.`);
// A simulated player uses the real input/update loop: no health, enemy or damage cheats.
let completed=0,dead=0,stalled=0,report=[];
for(let attempt=0;attempt<20;attempt++){
 const act=attempt<12?1:2;run(`meta=structuredClone(DEFAULT);meta.sound=false;newRun(${act});`);
 let frames=0;
 while(!['victory','dead'].includes(run('G.mode'))&&frames++<60*600){
  run(`{let p=G.p;if(G.mode==='dialog'&&G.talk){if(G.talk.step===0)talkChoose(G.room%2);else talkEnd();}else if(G.mode==='dialog'&&G.offers){takeBoon(G.offers[0].id);}else if(G.mode==='dialog'){resume();}if(G.mode==='play'){keys.clear();let enemies=G.enemies.filter(e=>e.hp>0).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x));let e=enemies[0];if(e){let dx=e.x-p.x,dy=e.y-p.y;if(Math.abs(dx)>75)keys.add(dx>0?'ArrowRight':'ArrowLeft');else p.face=dx>0?1:-1;if(dy<-80&&p.ground)pressed.add('jump');if(e.state==='windup'&&e.timer<.18&&Math.abs(dx)<210&&Math.abs(dy)<110&&p.parryCD<=0)pressed.add('parry');if(Math.abs(dx)<115&&Math.abs(dy)<85&&p.attackCD<=0)pressed.add('attack');if(Math.abs(dx)<180&&p.skillU<=0)pressed.add('skillU');if(Math.abs(dx)<530&&p.skillI<=0)pressed.add('skillI');if(G.run.laugh>=100)pressed.add('ult');}else if(G.cleared&&G.room!==7){if(G.room===6&&G.run.hp<G.run.maxHp&&G.run.gold>=25){G.run.gold-=25;G.run.hp=Math.min(G.run.maxHp,G.run.hp+40);}let door=G.doors[0];if(door){let dx=door.x-p.x;if(Math.abs(dx)>45)keys.add(dx>0?'ArrowRight':'ArrowLeft');else pressed.add('interact');}}}update(1/60);}`);
 }
 const mode=run('G.mode');if(mode==='victory')completed++;else if(mode==='dead')dead++;else stalled++;
 report.push({act,mode,room:run('G.room')+1,seconds:Math.round(frames/60),parries:run('G.run?.parries')});
}
console.log('SIMULATED CAMPAIGNS',JSON.stringify({completed,dead,stalled,runs:report}));
assert.equal(stalled,0,'no simulated run may get stuck');
