const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let seed=42;const math=Object.create(Math);math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const storage=new Map(),els=new Map();let proxy=new Proxy({measureText:s=>({width:s.length*10}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
const make=()=>({innerHTML:'',hidden:false,style:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},querySelector(){return make()},querySelectorAll(){return[]},addEventListener(){},focus(){},click(){},getContext:()=>proxy});
let context={console,Math:math,structuredClone,JSON,Blob,URL,setTimeout:()=>0,Image:class{complete=false;naturalWidth=0},requestAnimationFrame(){},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},window:{addEventListener(){}},navigator:{getGamepads:()=>[]},document:{querySelector:s=>{if(!els.has(s))els.set(s,make());return els.get(s)},addEventListener(){},activeElement:make(),documentElement:{},createElement:make()}};
vm.createContext(context);vm.runInContext('const ASSETS={harbor:"",hero:""};'+fs.readFileSync(require('node:path').join(__dirname,'../src/game.js'),'utf8'),context);const run=s=>vm.runInContext(s,context);let count=0;function test(name,f){f();count++;console.log('PASS',name)}function setup(){run('meta=structuredClone(DEFAULT);meta.sound=false;newRun();if(G.mode==="dialog")resume();G.enemies=[];G.p.x=150;G.p.y=650;G.p.ground=true;G.p.vy=0;');}function step(n=1){for(let i=0;i<n;i++)run('update(1/60)')}
test('hub, twelve room templates, eight-stage run and first combat render',()=>{run('hub();render()');assert.equal(run('G.mode'),'hub');run('newRun();render()');assert.equal(run('LAYOUTS.length'),12);assert.equal(run('G.run.rooms.length'),8);assert.equal(run('new Set(G.run.rooms).size'),8);assert.equal(run('G.enemies.length'),3);});
test('movement, grounded jump, double jump, no third jump',()=>{setup();run(`keys.add('ArrowRight')`);step(30);assert.ok(run('G.p.x')>250);run(`keys.clear();pressed.add('jump')`);step();assert.ok(run('G.p.vy')<0);run(`pressed.add('jump')`);step();assert.equal(run('G.p.jumps'),2);let vy=run('G.p.vy');run(`pressed.add('jump')`);step();assert.equal(run('G.p.jumps'),2);assert.ok(run('G.p.vy')>vy);step(120);assert.equal(run('G.p.y'),650);});
test('dodge blocks incoming damage and has cooldown',()=>{setup();run(`pressed.add('dash')`);step();let hp=run('G.run.hp');run('hurtPlayer(20,{x:200})');assert.equal(run('G.run.hp'),hp);assert.ok(run('G.p.dashCD')>.6);});
test('well-timed parry reflects attack, builds laughter and respects expiry',()=>{setup();run(`let foe=spawnEnemy('sailor',210,650);G.p.parry=.3;hurtPlayer(13,foe)`);assert.equal(run('G.run.hp'),100);assert.equal(run('G.run.parries'),1);assert.equal(run('G.run.laugh'),24);assert.equal(run('foe.maxHp-foe.hp'),38);run('G.p.parry=0;G.p.invul=0;hurtPlayer(13,foe)');assert.equal(run('G.run.hp'),87);});
test('three attacks have increasing damage and cooldown prevents spam',()=>{setup();run(`let dummy=spawnEnemy('boss',220,650);dummy.hp=dummy.maxHp=1000;doAttack()`);assert.equal(run('dummy.hp'),983);run('doAttack()');assert.equal(run('dummy.hp'),983);run('G.p.attackCD=0;doAttack();G.p.attackCD=0;doAttack()');assert.equal(run('dummy.hp'),933);});
test('skills apply cooldown; bombs expire and ultimate spends laughter',()=>{setup();run(`spawnEnemy('boss',220,650);useSkill('U')`);let hp=run('G.enemies[0].hp');run(`useSkill('U')`);assert.equal(run('G.enemies[0].hp'),hp);run(`useSkill('I');updateProjectiles(1.3)`);assert.equal(run('G.projectiles.length'),0);run('G.run.laugh=100;ultimate()');assert.equal(run('G.run.laugh'),0);assert.ok(run('G.enemies[0].hp')<hp);});
test('locked exits, clear state, reward choice and next-room transition',()=>{setup();run(`loadRoom(0);G.p.x=G.doors[0].x;G.p.y=650;interact()`);assert.equal(run('G.mode'),'play');assert.equal(run('G.room'),0);run('G.enemies.forEach(e=>killEnemy(e));G.hitstop=0');step();assert.equal(run('G.cleared'),true);run('interact()');assert.equal(run('G.mode'),'dialog');run('takeBoon(G.offers[0].id)');assert.equal(run('G.room'),1);assert.equal(run('G.run.boons.length'),1);assert.equal(run('G.mode'),'play');});
test('permanent upgrades, unlock and starting weapon survive a new run',()=>{setup();run(`meta.teeth=10;action('upgrade:health');meta.film=7;action('unlock');newRun()`);assert.equal(run('G.run.maxHp'),112);assert.equal(run('G.run.weapon'),'flail');assert.equal(run('meta.teeth'),8);assert.equal(run('meta.film'),2);assert.equal(run('validMeta(JSON.parse(localStorage.getItem(KEY)))'),true);assert.equal(run('validMeta({version:1})'),false);});
test('merchant charges once per successful purchase and correct room retained',()=>{setup();run(`loadRoom(6);G.run.gold=60;G.run.hp=30;action('buyheal')`);assert.equal(run('G.run.gold'),35);assert.equal(run('G.run.hp'),70);run(`action('buysmile')`);assert.equal(run('G.run.gold'),35);run(`G.run.gold=80;action('buysmile');takeBoon(G.offers[0].id)`);assert.equal(run('G.run.gold'),30);assert.equal(run('G.room'),6);});
test('death preserves meta, learns boss tell and returns to hub',()=>{setup();run(`loadRoom(7);meta.teeth=3;G.run.hp=1;hurtPlayer(30,G.boss)`);assert.equal(run('G.mode'),'dead');assert.equal(run('meta.bossKnown'),true);run('hub()');assert.equal(run('G.run'),null);assert.equal(run('meta.teeth'),3);});
test('boss victory and journal clue complete chapter without repeated rewards',()=>{setup();run(`loadRoom(7);killEnemy(G.boss)`);step(200);assert.equal(run('G.mode'),'victory');assert.equal(run('meta.wins'),1);assert.equal(run('meta.clues.includes("captain")'),true);step(100);assert.equal(run('meta.wins'),1);});
test('all room layouts and every UI state render without exceptions',()=>{setup();for(let i=0;i<12;i++)run(`G.layout=${i};render()`);for(let code of ['help()','resume()','journal()','resume()','pause()','resume()','upgradeMenu()','resume()','smithMenu()','resume()','loadRoom(6)','merchantMenu()','resume()','loadRoom(7)'])run(code+';render()');});
console.log(`${count} tests passed.`);
// A simulated player uses the real input/update loop: no health, enemy or damage cheats.
let completed=0,dead=0,stalled=0,report=[];
for(let attempt=0;attempt<12;attempt++){
 run(`meta=structuredClone(DEFAULT);meta.sound=false;newRun();`);
 let frames=0;
 while(!['victory','dead'].includes(run('G.mode'))&&frames++<60*600){
  run(`{let p=G.p;if(G.mode==='dialog'&&G.offers){takeBoon(G.offers[0].id);}else if(G.mode==='dialog'){resume();}if(G.mode==='play'){keys.clear();let enemies=G.enemies.filter(e=>e.hp>0).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x));let e=enemies[0];if(e){let dx=e.x-p.x,dy=e.y-p.y;if(Math.abs(dx)>75)keys.add(dx>0?'ArrowRight':'ArrowLeft');else p.face=dx>0?1:-1;if(dy<-80&&p.ground)pressed.add('jump');if(e.state==='windup'&&e.timer<.18&&Math.abs(dx)<210&&Math.abs(dy)<110&&p.parryCD<=0)pressed.add('parry');if(Math.abs(dx)<115&&Math.abs(dy)<85&&p.attackCD<=0)pressed.add('attack');if(Math.abs(dx)<180&&p.skillU<=0)pressed.add('skillU');if(Math.abs(dx)<530&&p.skillI<=0)pressed.add('skillI');if(G.run.laugh>=100)pressed.add('ult');}else if(G.cleared&&G.room!==7){if(G.room===6&&G.run.hp<G.run.maxHp&&G.run.gold>=25){G.run.gold-=25;G.run.hp=Math.min(G.run.maxHp,G.run.hp+40);}let door=G.doors[0];if(door){let dx=door.x-p.x;if(Math.abs(dx)>45)keys.add(dx>0?'ArrowRight':'ArrowLeft');else pressed.add('interact');}}}update(1/60);}`);
 }
 const mode=run('G.mode');if(mode==='victory')completed++;else if(mode==='dead')dead++;else stalled++;
 report.push({mode,room:run('G.room')+1,seconds:Math.round(frames/60),parries:run('G.run?.parries')});
}
console.log('SIMULATED CAMPAIGNS',JSON.stringify({completed,dead,stalled,runs:report}));
assert.equal(stalled,0,'no simulated run may get stuck');
